/**
 * US-META-001 — `roll index`: (re)generate `.roll/index.json`, the authoritative
 * ID→epic map the archive layout uses to place a card's deliverables under
 * `features/<epic>/<ID>/`. Also regenerates `features/index.html` (US-META-003).
 * Deterministic + idempotent.
 */
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { generateIndex } from "../lib/archive.js";

/** `roll index` — regenerate the backlog-derived ID→epic index + features root page. */
export function indexCommand(args: string[]): number {
  if (args.includes("--help") || args.includes("-h")) {
    process.stdout.write("Usage: roll index\n  Regenerate .roll/index.json + .roll/features/index.html\n");
    return 0;
  }
  const cwd = process.cwd();
  const stories = generateIndex(cwd);
  const n = Object.keys(stories).length;
  process.stdout.write(`index.json regenerated\n索引已重建\n  ${n} stories mapped to epics (.roll/index.json)\n`);

  // US-META-003: regenerate features/index.html
  const featuresDir = join(cwd, ".roll", "features");
  if (existsSync(featuresDir)) {
    const epics = new Map<string, string[]>();
    for (const [sid, epic] of Object.entries(stories)) {
      epics.set(epic, [...(epics.get(epic) || []), sid]);
    }
    // Also scan for story folders not in index.json
    try {
      for (const d of readdirSync(featuresDir)) {
        const epicDir = join(featuresDir, d);
        if (!statSync(epicDir).isDirectory()) continue;
        if (!epics.has(d)) epics.set(d, []);
        for (const s of readdirSync(epicDir)) {
          const storyDir = join(epicDir, s);
          if (!statSync(storyDir).isDirectory()) continue;
          if (/^(FIX|US|IDEA|REFACTOR)-/.test(s) && !epics.get(d)!.includes(s)) {
            epics.get(d)!.push(s);
          }
        }
      }
    } catch { /* best-effort */ }

    const rows: string[] = [];
    for (const [epic, storyList] of [...epics].sort()) {
      const unique = [...new Set(storyList)].sort();
      let delivered = 0;
      for (const s of unique) {
        const latest = join(featuresDir, epic, s, "latest");
        try { if (statSync(latest).isDirectory() || statSync(latest).isSymbolicLink()) delivered++; } catch { /* */ }
      }
      const links = unique.slice(0, 20).map((s) => `<a href="${epic}/${s}/index.html">${s}</a>`).join(", ");
      const more = unique.length > 20 ? ` ... +${unique.length - 20} more` : "";
      rows.push(`<tr>\n<td><strong><a href="${epic}/">${epic}</a></strong></td>\n<td>${unique.length} stories (${delivered} delivered)</td>\n<td style="font-size:0.85em">${links}${more}</td>\n</tr>`);
    }

    const html = `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<title>Roll Features Index</title>\n` +
      `<style>body{font-family:system-ui;max-width:1000px;margin:2rem auto;padding:0 1rem;` +
      `line-height:1.6;color:#1a1a1a}h1{color:#333}table{width:100%;border-collapse:collapse}` +
      `th,td{padding:8px 12px;text-align:left;border-bottom:1px solid #e0e0e0}` +
      `th{background:#f5f5f5}tr:hover{background:#fafafa}` +
      `a{color:#0969da;text-decoration:none}a:hover{text-decoration:underline}` +
      `footer{color:#666;font-size:.85rem;margin-top:3rem;border-top:1px solid #eee;padding-top:1rem}</style>\n` +
      `</head>\n<body>\n<h1>🎯 Roll Features Index</h1>\n<p>${epics.size} epics · ${n} stories</p>\n` +
      `<table><thead><tr><th>Epic</th><th>Stories</th><th>Recent</th></tr></thead>\n` +
      `<tbody>\n${rows.join("\n")}\n</tbody></table>\n` +
      `<footer>Generated by roll index</footer>\n</body>\n</html>\n`;

    try {
      writeFileSync(join(featuresDir, "index.html"), html, "utf8");
      process.stdout.write(`features/index.html regenerated\n`);
    } catch { /* best-effort */ }
  }

  return 0;
}
