/**
 * `roll loop on|off|pause|resume` — US-LOOP-009: the TS scheduling surface that
 * swaps the loop's runtime heart from the v2 bash inner to `roll loop run-once`.
 *
 * DELIBERATE v2 DIVERGENCE (whitelisted in the AGENTS.md bridge table):
 *   - The generated loop runner is a SELF-CONTAINED wrapper: PATH bootstrap,
 *     PAUSE marker, active window, caffeinate, then `roll loop run-once`. The
 *     v2 outer/inner pair (tmux popup, baked agent argv, `source bin/roll`,
 *     formatter/usage/eval side-cars) is retired — run-once owns the cycle
 *     (lock, heartbeat, watchdog, events/runs/cycle-logs) natively.
 *   - No bash-engine function is referenced by the generated script. The v2
 *     outer template called `_loop_migrate_legacy_paths` & co. without sourcing
 *     them — `command not found` on every manual run (FIX-197).
 *   - The dream service is NOT regenerated here (its runner drives an agent
 *     skill command — bash-era surface, see FIX-197 lineage). `loop off` still
 *     boots it out so no zombie schedule survives a shutdown.
 *
 * KEPT contracts (so status/dashboard/brief keep reading the same world):
 *   - runner path  : <shared>/loop/run-<slug>.sh   (pr: <shared>/pr/run-<slug>.sh)
 *   - plist        : ~/Library/LaunchAgents/com.roll.<svc>.<slug>.plist via
 *                    infra plistContent (byte-shape of _write_launchd_plist)
 *   - machine log  : <project>/.roll/loop/cron.log  (pr: pr.log)
 *   - PAUSE marker : <project>/.roll/loop/PAUSE-<slug>
 *   - launchctl    : enable/bootstrap + bootout pairs (FIX-027/FIX-098 dance)
 *   - loop period  : .roll/local.yaml `loop_schedule.period_minutes` (default 30)
 */
import {
  type LaunchctlResult,
  launchdLabel,
  launchdPlistPath,
  plistContent,
  reinstall as launchdReinstall,
  uninstall as launchdUninstall,
  projectIdentity,
} from "@roll/infra";
import { spawn } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

// ─── injectable deps (tests fake launchd + identity + paths) ─────────────────
export interface LoopSchedDeps {
  identity: () => Promise<{ path: string; slug: string }>;
  uid: () => number;
  sharedRoot: () => string;
  launchdDir: () => string;
  launchd: {
    reinstall: (uid: number, label: string, plist: string) => Promise<LaunchctlResult>;
    uninstall: (uid: number, label: string) => Promise<LaunchctlResult>;
  };
  /** Run the generated loop runner once, FORCE env set (loop now). */
  execRunner?: (runnerPath: string) => Promise<number>;
}

function realDeps(): LoopSchedDeps {
  return {
    identity: () => projectIdentity(),
    uid: () => process.getuid?.() ?? 501,
    sharedRoot: () => process.env["ROLL_SHARED_ROOT"] || join(homedir(), ".shared", "roll"),
    launchdDir: () => join(homedir(), "Library", "LaunchAgents"),
    launchd: { reinstall: launchdReinstall, uninstall: launchdUninstall },
    execRunner: () =>
      new Promise((resolve) => {
        // Re-enter THIS cli (`loop run-once`) in the foreground — not the
        // launchd runner script, whose whole job is redirecting to cron.log.
        const cli = process.argv[1] ?? "";
        const child = spawn(process.execPath, [cli, "loop", "run-once"], {
          stdio: "inherit",
          env: { ...process.env, ROLL_LOOP_FORCE: "1", ROLL_LOOP_STREAM: "1" },
        });
        child.on("exit", (code) => resolve(code ?? 1));
        child.on("error", () => resolve(1));
      }),
  };
}

// ─── templates ────────────────────────────────────────────────────────────────

export interface LoopRunnerInput {
  projectPath: string;
  slug: string;
  /** Active window [start, end) in hours; full window = 0..24. */
  activeStart: number;
  activeEnd: number;
}

/**
 * The v3 loop runner: a thin, self-contained launchd wrapper around
 * `roll loop run-once`. Everything cycle-shaped (lock, heartbeat, watchdog,
 * worktree, agent, publish, events/runs) lives in run-once — NOT here.
 */
export function buildLoopRunnerScript(input: LoopRunnerInput): string {
  const rt = `${input.projectPath}/.roll/loop`;
  return `#!/bin/bash -l
# roll v3 loop runner — generated by \`roll loop on\` (US-LOOP-009).
# Self-contained wrapper: the cycle heart is \`roll loop run-once\` (TS).
# Portable PATH: launchd delivers a bare PATH missing brew/local tools. Idempotent.
for _d in /opt/homebrew/bin /usr/local/bin /opt/local/bin "$HOME/.local/bin" "$HOME/.kimi-code/bin"; do
  case ":$PATH:" in *":$_d:"*) ;; *) [ -d "$_d" ] && PATH="$_d:$PATH" ;; esac
done
export PATH
RT="${rt}"
LOG="$RT/cron.log"
mkdir -p "$RT"
# Pause marker — written by \`roll loop pause\`, removed by \`roll loop resume\`.
if [ -f "$RT/PAUSE-${input.slug}" ]; then exit 0; fi
# Active window [${input.activeStart},${input.activeEnd}) — ROLL_LOOP_FORCE (manual \`roll loop now\`) bypasses.
# 10# forces base-10: \`date +%H\` yields "08"/"09" which printf %d rejects as octal (v2 latent bug, fixed here).
if [ -z "$ROLL_LOOP_FORCE" ]; then
  h=$((10#$(date +%H)))
  if [ "$h" -lt ${input.activeStart} ] || [ "$h" -ge ${input.activeEnd} ]; then exit 0; fi
fi
# Keep the box awake for the duration of the cycle.
caffeinate -i -w $$ 2>/dev/null &
ROLL_BIN="\${ROLL_BIN:-$(command -v roll || echo /opt/homebrew/bin/roll)}"
cd "${input.projectPath}" || exit 0
echo "[$(date '+%Y-%m-%dT%H:%M:%S%z')] cycle start (v3 run-once)" >> "$LOG"
"$ROLL_BIN" loop run-once >> "$LOG" 2>&1
rc=$?
echo "[$(date '+%Y-%m-%dT%H:%M:%S%z')] cycle end rc=$rc" >> "$LOG"
exit 0
`;
}

export interface PrRunnerInput {
  projectPath: string;
  /** The installed bash engine the PR inbox orchestrator lives in. */
  rollBin: string;
}

/**
 * PR-loop runner — transcription of the v2 `_write_pr_loop_runner_script`
 * shape (bin/roll 8306-8341): portable PATH, single-flight pid:ts lock with
 * 15-min staleness self-heal, then drive `_loop_pr_inbox` through the bash
 * engine. Unchanged behavior; only the GENERATOR moved to TS.
 */
export function buildPrRunnerScript(input: PrRunnerInput): string {
  const lock = `${input.projectPath}/.roll/loop/.pr-loop.lock`;
  const log = `${input.projectPath}/.roll/loop/pr.log`;
  return `#!/bin/bash -l
set -o pipefail
# Portable PATH: launchd delivers a bare PATH missing brew/local tools. Idempotent.
for _d in /opt/homebrew/bin /usr/local/bin /opt/local/bin "$HOME/.local/bin" "$HOME/.kimi-code/bin"; do
  case ":$PATH:" in *":$_d:"*) ;; *) [ -d "$_d" ] && PATH="$_d:$PATH" ;; esac
done
export PATH
# Single-flight re-entry guard: one PR-loop pass at a time. 5-min cadence;
# 15-min (900s) staleness so a crashed/hung pass self-heals on the next tick.
LOCK="${lock}"
mkdir -p "$(dirname "$LOCK")"
if [ -f "$LOCK" ]; then
  _pp=""; _pt=""
  IFS=: read -r _pp _pt < "$LOCK" 2>/dev/null || true
  _now=$(date -u +%s)
  if [ -n "$_pp" ] && [ -n "$_pt" ] && kill -0 "$_pp" 2>/dev/null && [ "$((_now - _pt))" -lt 900 ]; then
    exit 0
  fi
  rm -f "$LOCK"
fi
printf '%s:%s\\n' "$$" "$(date -u +%s)" > "$LOCK"
trap 'rm -f "$LOCK"' EXIT
cd "${input.projectPath}" || exit 0
bash "${input.rollBin}" _loop_pr_inbox >> "${log}" 2>&1 || true
`;
}

/** Read `loop_schedule.period_minutes` from local.yaml text; 30 when absent. */
export function parseLoopPeriodMinutes(text: string): number {
  const lines = text.split("\n");
  let inSection = false;
  for (const raw of lines) {
    const line = raw.replace(/\r$/, "");
    if (line.trim() === "" || line.trimStart().startsWith("#")) continue;
    const indent = line.length - line.trimStart().length;
    if (!inSection) {
      if (indent === 0 && /^loop_schedule:\s*$/.test(line.trim())) inSection = true;
      continue;
    }
    if (indent === 0) break;
    const m = /^period_minutes:\s*(\d+)\s*(?:#.*)?$/.exec(line.trim());
    if (m) {
      const n = Number(m[1]);
      if (Number.isFinite(n) && n >= 1) return n;
    }
  }
  return 30;
}

// ─── helpers ──────────────────────────────────────────────────────────────────

function pathValue(): string {
  // The plist EnvironmentVariables PATH — brew/local dirs first, system after
  // (mirrors the live v2-generated plist; the runner self-repairs PATH anyway).
  const home = homedir();
  return [
    "/opt/homebrew/bin",
    `${home}/.local/bin`,
    `${home}/.kimi-code/bin`,
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
  ].join(":");
}

function writeExecutable(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, { mode: 0o755 });
}

function pauseMarkerPath(projectPath: string, slug: string): string {
  return join(projectPath, ".roll", "loop", `PAUSE-${slug}`);
}

/** Resolve the installed bash engine for the PR runner (package bin/roll). */
function installedRollBashBin(): string {
  // The TS CLI and bin/roll ship in the same package; walk from this module.
  // dist layout: <pkg>/packages/cli/dist/commands/loop-sched.js → <pkg>/bin/roll
  let dir = dirname(new URL(import.meta.url).pathname);
  for (let i = 0; i < 10; i++) {
    const candidate = join(dir, "bin", "roll");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return "/opt/homebrew/lib/node_modules/@seanyao/roll/bin/roll";
}

// ─── commands ─────────────────────────────────────────────────────────────────

const LOOP_SERVICES = ["loop", "dream", "pr"] as const;

/** `roll loop on` — generate v3 runners + plists, (re)load loop & pr. */
export async function loopOnCommand(_args: string[], deps: LoopSchedDeps = realDeps()): Promise<number> {
  const id = await deps.identity();
  const shared = deps.sharedRoot();
  const ld = deps.launchdDir();
  const uid = deps.uid();
  mkdirSync(ld, { recursive: true });

  // loop period from project local.yaml (live default: 30).
  let period = 30;
  const localYaml = join(id.path, ".roll", "local.yaml");
  if (existsSync(localYaml)) {
    try {
      period = parseLoopPeriodMinutes(readFileSync(localYaml, "utf8"));
    } catch {
      /* default */
    }
  }

  // 1. loop service — the v3 heart.
  const loopRunner = join(shared, "loop", `run-${id.slug}.sh`);
  writeExecutable(
    loopRunner,
    buildLoopRunnerScript({ projectPath: id.path, slug: id.slug, activeStart: 0, activeEnd: 24 }),
  );
  const loopLabel = launchdLabel("loop", id.slug);
  const loopPlist = launchdPlistPath("loop", id.slug, ld);
  writeFileSync(
    loopPlist,
    plistContent({
      label: loopLabel,
      runnerScript: loopRunner,
      projectPath: id.path,
      pathValue: pathValue(),
      schedule: { kind: "interval", periodMinutes: period },
    }),
  );
  await deps.launchd.reinstall(uid, loopLabel, loopPlist);

  // 2. pr service — v2-shape tick every 5 min.
  const prRunner = join(shared, "pr", `run-${id.slug}.sh`);
  writeExecutable(prRunner, buildPrRunnerScript({ projectPath: id.path, rollBin: installedRollBashBin() }));
  const prLabel = launchdLabel("pr", id.slug);
  const prPlist = launchdPlistPath("pr", id.slug, ld);
  writeFileSync(
    prPlist,
    plistContent({
      label: prLabel,
      runnerScript: prRunner,
      projectPath: id.path,
      pathValue: pathValue(),
      schedule: { kind: "interval", periodMinutes: 5 },
    }),
  );
  await deps.launchd.reinstall(uid, prLabel, prPlist);

  process.stdout.write(
    [
      `Loop enabled — cycle heart: roll loop run-once (v3)`,
      `Loop 已启用 — 周期心脏:roll loop run-once(v3)`,
      `  • roll-loop  every ${period}min  /  每 ${period} 分钟`,
      `  • pr-loop    every 5min  /  每 5 分钟`,
      `  • dream      untouched (legacy runner, see FIX-197)  /  未改动(旧 runner,见 FIX-197)`,
      ``,
    ].join("\n"),
  );
  return 0;
}

/** `roll loop off` — boot out every roll service for this project. */
export async function loopOffCommand(_args: string[], deps: LoopSchedDeps = realDeps()): Promise<number> {
  const id = await deps.identity();
  const uid = deps.uid();
  for (const svc of LOOP_SERVICES) {
    await deps.launchd.uninstall(uid, launchdLabel(svc, id.slug));
  }
  process.stdout.write(`Loop disabled (loop/dream/pr booted out)\nLoop 已停用(loop/dream/pr 均已卸载)\n`);
  return 0;
}

/** `roll loop pause` — write the PAUSE marker the runner honors. */
export async function loopPauseCommand(_args: string[], deps: LoopSchedDeps = realDeps()): Promise<number> {
  const id = await deps.identity();
  const marker = pauseMarkerPath(id.path, id.slug);
  mkdirSync(dirname(marker), { recursive: true });
  const already = existsSync(marker);
  if (!already) writeFileSync(marker, `${new Date().toISOString()}\n`);
  process.stdout.write(
    already
      ? `Loop already paused\nLoop 已处于暂停\n`
      : `Loop paused — next scheduled cycles will skip\nLoop 已暂停 — 后续排程周期将跳过\n`,
  );
  return 0;
}

/** `roll loop resume` — remove the PAUSE marker. */
export async function loopResumeCommand(_args: string[], deps: LoopSchedDeps = realDeps()): Promise<number> {
  const id = await deps.identity();
  const marker = pauseMarkerPath(id.path, id.slug);
  const existed = existsSync(marker);
  rmSync(marker, { force: true });
  process.stdout.write(
    existed
      ? `Loop resumed — scheduling active again\nLoop 已恢复 — 排程重新生效\n`
      : `Loop was not paused\nLoop 本就未暂停\n`,
  );
  return 0;
}

// ─── FIX-197: loop now + legacy-runner self-heal ──────────────────────────────

/**
 * A v2-generation outer runner: it bare-calls bash-engine functions that were
 * never sourced into it (`_loop_migrate_legacy_paths` & co.) — `command not
 * found` on every manual run, and its PAUSE check silently no-ops. Any runner
 * that does not delegate to `loop run-once` is treated as legacy.
 */
export function isLegacyRunner(text: string): boolean {
  return /_loop_migrate_legacy_paths|_loop_runtime_dir/.test(text) || !text.includes("loop run-once");
}

/**
 * `roll loop now` — force one cycle immediately (FIX-197 self-heal included):
 * a missing or v2-legacy runner is regenerated via `loop on` first (with a
 * note), then the v3 runner executes synchronously with ROLL_LOOP_FORCE=1.
 * DELIBERATE divergence from v2: no tmux popup — output streams inline and the
 * cycle transcript lands in .roll/loop/cron.log (same whitelist as US-LOOP-009).
 */
export async function loopNowCommand(_args: string[], deps: LoopSchedDeps = realDeps()): Promise<number> {
  const id = await deps.identity();
  const runner = join(deps.sharedRoot(), "loop", `run-${id.slug}.sh`);

  let legacy = false;
  if (existsSync(runner)) {
    try {
      legacy = isLegacyRunner(readFileSync(runner, "utf8"));
    } catch {
      legacy = true;
    }
  }
  if (!existsSync(runner) || legacy) {
    process.stdout.write(
      legacy
        ? `Legacy v2 runner detected — regenerating templates (FIX-197)\n检测到 v2 旧版 runner — 正在再生成模板（FIX-197）\n`
        : `No runner yet — generating templates\n尚无 runner — 正在生成模板\n`,
    );
    const rc = await loopOnCommand([], deps);
    if (rc !== 0) return rc;
  }

  // US-PORT-011: `loop now` is a FOREGROUND experience — the cycle runs in
  // this terminal with the agent transcript streaming live (ROLL_LOOP_STREAM),
  // no popup, no tail, no silence. launchd keeps using the silent runner.
  process.stdout.write(
    `Starting one loop cycle — live transcript below\n强制启动一个 loop 周期 — 实时转录如下\n\n`,
  );
  const exec = deps.execRunner;
  if (exec === undefined) {
    process.stderr.write("loop now: no runner executor available\n");
    return 1;
  }
  return exec(runner);
}
