/**
 * `roll migrate-features` — US-META-007: backfill spec.md + index.html
 * for existing stories that have attest folders but no definition files.
 *
 * Reads .roll/index.json (story→epic), walks .roll/features/, and generates
 * missing spec.md + index.html skeletons. Idempotent — existing files are
 * never overwritten. Skeletons come from the shared story-page generator, so
 * backfilled cards are identical to `roll idea`-created ones (and attest's
 * delivery-section update matches them).
 *
 * `--refresh-html` additionally REGENERATES every story's index.html in the
 * current page design (spec.md is still never overwritten — it is the human
 * source; the html is a derived artifact). Delivery state is re-derived from
 * the archive itself: a `latest` run with an attestation report flips the
 * Delivery phase back to done, pointing at the report.
 */
import { existsSync, mkdirSync, readFileSync, readlinkSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { bi } from "@roll/core";
import { readIndex, reportFileName } from "../lib/archive.js";
import { markPhaseDone, renderSpecMd, renderStoryPage } from "../lib/story-page.js";

/** Pull `title:` / `created:` out of an existing spec.md frontmatter (line scan). */
function specFrontmatter(specFile: string): { title?: string; created?: string } {
  try {
    const lines = readFileSync(specFile, "utf8").split("\n").slice(0, 12);
    const pick = (key: string): string | undefined => {
      const row = lines.find((l) => l.startsWith(`${key}: `));
      return row?.slice(key.length + 2).trim();
    };
    return { title: pick("title"), created: pick("created") };
  } catch {
    return {};
  }
}

export function migrateFeaturesCommand(args: string[]): number {
  const refresh = args.includes("--refresh-html");
  const cwd = process.cwd();
  if (!existsSync(join(cwd, ".roll", "index.json"))) {
    process.stderr.write("migrate-features: .roll/index.json not found\n");
    return 1;
  }
  const stories = readIndex(cwd);

  const root = join(cwd, ".roll", "features");
  const today = new Date().toISOString().slice(0, 10);
  let specCreated = 0;
  let htmlWritten = 0;
  let skipped = 0;

  for (const [storyId, epic] of Object.entries(stories)) {
    const storyDir = join(root, epic, storyId);
    const specFile = join(storyDir, "spec.md");

    // Ensure directory exists (may have been created by attest delivery).
    if (!existsSync(storyDir)) {
      // Check for a .md file in epic root for this story.
      const mdFile = join(root, epic, `${storyId}.md`);
      if (existsSync(mdFile)) {
        try { mkdirSync(storyDir, { recursive: true }); } catch { skipped++; continue; }
      } else {
        skipped++;
        continue;
      }
    }

    if (!existsSync(specFile)) {
      writeFileSync(
        specFile,
        renderSpecMd({
          id: storyId,
          epic,
          created: today,
          note: "Auto-generated by migrate-features (US-META-007).",
        }),
        "utf8",
      );
      specCreated++;
    }

    const htmlFile = join(storyDir, "index.html");
    if (!existsSync(htmlFile) || refresh) {
      // Keep the human-authored bits: title + original creation date live in spec.md.
      const fm = specFrontmatter(specFile);
      const card = { id: storyId, epic, created: fm.created ?? today, ...(fm.title !== undefined ? { title: fm.title } : {}) };
      let html = renderStoryPage(card);
      // Delivery state is re-derivable from the archive: latest run + report.
      const latest = join(storyDir, "latest");
      const report = join(latest, reportFileName(storyId));
      if (existsSync(report)) {
        let runRel = "latest";
        try { runRel = readlinkSync(latest); } catch { /* real dir — link via latest/ */ }
        const deliveredOn = statSync(report).mtime.toISOString().slice(0, 10);
        html = markPhaseDone(
          html,
          "delivery",
          `<p><a href="${runRel}/${reportFileName(storyId)}">${bi("Attestation report", "验收报告")}</a></p>\n` +
            `<p class="muted">${bi("Delivered", "交付于")} ${deliveredOn}</p>\n`,
        );
      }
      writeFileSync(htmlFile, html, "utf8");
      htmlWritten++;
    }
  }

  process.stdout.write(
    `migrate-features: ${specCreated} spec.md + ${htmlWritten} index.html ${refresh ? "written" : "created"}, ${skipped} skipped\n`,
  );
  return 0;
}
