/**
 * `roll migrate-features` — US-META-007: backfill spec.md + index.html
 * for existing stories that have attest folders but no definition files.
 *
 * Reads .roll/index.json (story→epic), walks .roll/features/, and generates
 * missing spec.md + index.html skeletons. Idempotent — existing files are
 * never overwritten. Skeletons come from the shared story-page generator, so
 * backfilled cards are identical to `roll idea`-created ones (and attest's
 * delivery-section update matches them).
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { readIndex } from "../lib/archive.js";
import { renderSpecMd, renderStoryPage } from "../lib/story-page.js";

export function migrateFeaturesCommand(_args: string[]): number {
  const cwd = process.cwd();
  if (!existsSync(join(cwd, ".roll", "index.json"))) {
    process.stderr.write("migrate-features: .roll/index.json not found\n");
    return 1;
  }
  const stories = readIndex(cwd);

  const root = join(cwd, ".roll", "features");
  const today = new Date().toISOString().slice(0, 10);
  let specCreated = 0;
  let htmlCreated = 0;
  let skipped = 0;

  for (const [storyId, epic] of Object.entries(stories)) {
    const storyDir = join(root, epic, storyId);
    const specFile = join(storyDir, "spec.md");

    // Ensure directory exists (may have been created by attest delivery).
    if (!existsSync(storyDir)) {
      // Check for a .md file in epic root for this story.
      const mdFile = join(root, epic, `${storyId}.md`);
      if (existsSync(mdFile)) {
        try { mkdirSync(storyDir, { recursive: true }); } catch { skipped++; continue; }
      } else {
        skipped++;
        continue;
      }
    }

    const card = {
      id: storyId,
      epic,
      created: today,
      note: "Auto-generated by migrate-features (US-META-007).",
    };
    if (!existsSync(specFile)) {
      writeFileSync(specFile, renderSpecMd(card), "utf8");
      specCreated++;
    }

    const htmlFile = join(storyDir, "index.html");
    if (!existsSync(htmlFile)) {
      writeFileSync(htmlFile, renderStoryPage(card), "utf8");
      htmlCreated++;
    }
  }

  process.stdout.write(
    `migrate-features: ${specCreated} spec.md + ${htmlCreated} index.html created, ${skipped} skipped\n`,
  );
  return 0;
}
