/**
 * `roll migrate-features` — US-META-007: backfill spec.md + index.html
 * for existing stories that have attest folders but no definition files.
 *
 * Reads .roll/index.json (story→epic), walks .roll/features/, and generates
 * missing spec.md + index.html skeletons. Idempotent — existing files are
 * never overwritten.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function migrateFeaturesCommand(_args: string[]): number {
  const cwd = process.cwd();
  const indexFile = join(cwd, ".roll", "index.json");
  if (!existsSync(indexFile)) {
    process.stderr.write("migrate-features: .roll/index.json not found\n");
    return 1;
  }

  let idx: { stories: Record<string, string> };
  try {
    idx = JSON.parse(readFileSync(indexFile, "utf8"));
  } catch {
    process.stderr.write("migrate-features: failed to parse .roll/index.json\n");
    return 1;
  }

  const root = join(cwd, ".roll", "features");
  let specCreated = 0;
  let htmlCreated = 0;
  let skipped = 0;

  for (const [storyId, epic] of Object.entries(idx.stories)) {
    const storyDir = join(root, epic, storyId);
    const specFile = join(storyDir, "spec.md");

    // Ensure directory exists (may have been created by attest delivery).
    if (!existsSync(storyDir)) {
      // Check for a .md file in epic root for this story.
      const mdFile = join(root, epic, `${storyId}.md`);
      if (existsSync(mdFile)) {
        try { mkdirSync(storyDir, { recursive: true }); } catch { skipped++; continue; }
      } else {
        skipped++;
        continue;
      }
    }

    if (!existsSync(specFile)) {
      const today = new Date().toISOString().slice(0, 10);
      const kind = storyId.startsWith("FIX") ? "fix" : storyId.startsWith("US") ? "us" :
                   storyId.startsWith("REFACTOR") ? "refactor" : "unknown";
      writeFileSync(specFile,
        `---\nid: ${storyId}\ntype: ${kind}\nepic: ${epic}\ncreated: ${today}\n---\n\n` +
        `# ${storyId}\n\n> Auto-generated by migrate-features (US-META-007).\n`, "utf8");
      specCreated++;
    }

    const htmlFile = join(storyDir, "index.html");
    if (!existsSync(htmlFile)) {
      const today = new Date().toISOString().slice(0, 10);
      const escapedTitle = storyId.replace(/"/g, "&quot;");
      writeFileSync(htmlFile,
        `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n` +
        `<title>${escapedTitle}</title>\n` +
        `<style>body{font-family:system-ui;max-width:900px;margin:2rem auto;padding:0 1rem;` +
        `line-height:1.6}section{margin:2rem 0;padding:1rem;border-left:3px solid #ddd}` +
        `.empty{color:#999;font-style:italic}footer{color:#666;font-size:.85rem;` +
        `margin-top:3rem;border-top:1px solid #eee;padding-top:1rem}</style>\n` +
        `</head>\n<body>\n<h1>${escapedTitle}</h1>\n` +
        `<section id="spec"><h2>Definition</h2><p class="empty">See spec.md</p></section>\n` +
        `<section id="design"><h2>Design</h2><p class="empty">Not yet started</p></section>\n` +
        `<section id="runs"><h2>Execution</h2><p class="empty">No cycles yet</p></section>\n` +
        `<section id="delivery"><h2>Delivery</h2><p class="empty">Not yet delivered</p></section>\n` +
        `<section id="notes"><h2>Retrospective</h2><p class="empty">Not yet written</p></section>\n` +
        `<footer>Generated ${today}</footer>\n</body>\n</html>\n`, "utf8");
      htmlCreated++;
    }
  }

  process.stdout.write(
    `migrate-features: ${specCreated} spec.md + ${htmlCreated} index.html created, ${skipped} skipped\n`,
  );
  return 0;
}
