/**
 * `roll skills` — TS port of bin/roll cmd_skills (1655-1693) plus the
 * _skills_catalog_generate / _skill_frontmatter_field / _skills_catalog_path
 * helpers (1567-1653). Subcommands: audit, sync, generate | gen, check, help.
 *
 * US-DOSSIER-036 elevates `roll skills` to a first-class observation+sync
 * surface (the build spec is authoritative; it overrides command-surface-round2
 * which demotes skills to T2):
 *   audit:    (US-DOSSIER-032) run the strict skills audit — the SAME yardstick
 *             the machine-global Skills page and `scripts/audit-skills.mjs` use.
 *             Reports skills · violations · hub lines + the four invocation
 *             groups (delivery/quality/observe/lifecycle). `--json` emits the
 *             machine view (same computation); `--strict` exits 1 on violations.
 *   sync:     write the projected catalog to guide/skills.md — the install/sync
 *             action (same write `roll setup skills` performs).
 *
 * The legacy callers keep working unchanged (AC2): `generate`/`gen` (the
 * `roll setup skills` redirect target) and `check` (the `roll doctor skills`
 * redirect target), including the install-tree skip path.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { resolveLang, t, v2Catalog, type Lang } from "@roll/spec";
import { repoRoot } from "../bridge.js";
import { collectSkillsPanel, type SkillGroup, type SkillsPanelVM } from "../lib/skills-panel.js";

function pkgDir(): string {
  return process.env["ROLL_PKG_DIR"] ?? repoRoot();
}

function catalogPath(): string {
  return join(pkgDir(), "guide", "skills.md");
}

/** FIX-276: an installed package ships no guide/ source dir — there is no
 *  catalog to maintain there. Generate/check must skip with a one-line notice
 *  (exit 0) instead of crashing with a raw ENOENT while WRITING into the
 *  global install tree. */
function isInstallTree(): boolean {
  return !existsSync(join(pkgDir(), "guide"));
}

function installSkipNotice(): void {
  info("skills catalog lives in the source repo — nothing to maintain on an installed roll");
  info("技能目录清单在源码仓维护——安装环境无需生成");
}

function skillsDir(): string {
  return join(pkgDir(), "skills");
}

/**
 * Port of _skill_frontmatter_field's awk: read the FIRST `---`-delimited
 * frontmatter block of a SKILL.md and return scalar field `field`. Supports
 * block scalars (`|`/`>` and ±/∓ chomping variants): subsequent more-indented
 * lines fold into a single space-separated string. Strips one matching pair of
 * surrounding quotes. Empty string when absent or file has no frontmatter.
 */
export function frontmatterField(file: string, field: string): string {
  const lines = readFileSync(file, "utf8").split("\n");
  if (lines.length === 0 || lines[0] !== "---") return "";
  let collecting = false;
  let val = "";
  // Start scanning after the opening `---` (awk: NR==1 infm=1; next).
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i] ?? "";
    if (collecting) {
      // A non-indented line or the closing --- (ignoring trailing ws) ends it.
      if (/^[^ \t]/.test(line) || /^---[ \t]*$/.test(line)) {
        return val;
      }
      const trimmed = line.replace(/^[ \t]+/, "").replace(/[ \t]+$/, "");
      if (trimmed === "") continue;
      val = val === "" ? trimmed : val + " " + trimmed;
      continue;
    }
    if (line === "---") return ""; // closing fence before field found
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).replace(/^[ \t]+|[ \t]+$/g, "");
    if (key !== field) continue;
    let v = line.slice(idx + 1).replace(/^[ \t]+/, "").replace(/[ \t]+$/, "");
    if (["|", ">", "|-", ">-", "|+", ">+"].includes(v)) {
      collecting = true;
      val = "";
      continue;
    }
    if (/^".*"$/.test(v) || /^'.*'$/.test(v)) {
      v = v.slice(1, -1);
    }
    return v;
  }
  // EOF mid-block-scalar: emit what we collected (awk END block).
  if (collecting) return val;
  return "";
}

/** Port of _skills_catalog_generate: deterministic lexicographic dir order. */
export function generateCatalog(): string {
  const out: string[] = [];
  out.push("# Roll Skill Catalog");
  out.push("");
  out.push("> GENERATED by `roll setup skills` — do not edit by hand.");
  out.push("> 由 `roll setup skills` 生成 — 请勿手工编辑。");
  out.push(">");
  out.push("> Source of truth: each skill's `skills/<name>/SKILL.md` frontmatter.");
  out.push("> 事实源：各 skill 的 `skills/<name>/SKILL.md` frontmatter。");
  out.push("");
  out.push("| Skill | Description |");
  out.push("|-------|-------------|");
  const dir = skillsDir();
  let entries: string[] = [];
  try {
    // bash `for d in "$skills_dir"/*/` globs in sorted (lexicographic) order.
    entries = readdirSync(dir).sort();
  } catch {
    entries = [];
  }
  for (const name of entries) {
    const skillDir = join(dir, name);
    try {
      if (!statSync(skillDir).isDirectory()) continue;
    } catch {
      continue;
    }
    const skillMd = join(skillDir, "SKILL.md");
    if (!existsSync(skillMd)) continue;
    let nm = frontmatterField(skillMd, "name");
    if (nm === "") nm = name; // basename fallback
    let desc = frontmatterField(skillMd, "description");
    desc = desc.replaceAll("|", "\\|"); // escape table pipes
    out.push(`| \`${nm}\` | ${desc} |`);
  }
  return out.join("\n") + "\n";
}

function info(line: string): void {
  const noColor = (process.env["NO_COLOR"] ?? "") !== "";
  const CYAN = noColor ? "" : "\x1b[0;36m";
  const NC = noColor ? "" : "\x1b[0m";
  process.stdout.write(`${CYAN}[roll]${NC} ${line}\n`);
}

function err(line: string): void {
  const noColor = (process.env["NO_COLOR"] ?? "") !== "";
  const RED = noColor ? "" : "\x1b[0;31m";
  const NC = noColor ? "" : "\x1b[0m";
  process.stderr.write(`${RED}[roll]${NC} ${line}\n`);
}

function msgLang(): Lang {
  return resolveLang({
    rollLang: process.env["ROLL_LANG"],
    lcAll: process.env["LC_ALL"],
    lang: process.env["LANG"],
  });
}

const GROUP_LABEL: Record<SkillGroup, { en: string; zh: string }> = {
  delivery: { en: "delivery", zh: "交付" },
  quality: { en: "quality", zh: "质量" },
  observe: { en: "observe", zh: "观测" },
  lifecycle: { en: "lifecycle", zh: "生命周期" },
};

/** The project root the skills panel reads (skills/ on disk + self-score notes). */
function projectRoot(): string {
  // ROLL_PKG_DIR (the source repo) carries the skills/ catalog; fall back to the
  // bridge repoRoot. The skills panel reads `<root>/skills` + `<root>/.roll`.
  return process.env["ROLL_PKG_DIR"] ?? repoRoot();
}

/**
 * Human render for `roll skills audit` (AC1): the summary bar — skills ·
 * violations · hub lines — then the four invocation groups, each a header line
 * and one line per skill (`name  ×usage  <violations|ok>`). EN + 中 on separate
 * lines (AC8). When the audit could not run, violations reads `unknown`, never a
 * silent 0 (the panel's AC4 contract carries through).
 */
function renderAuditPanel(vm: SkillsPanelVM, lang: Lang): string {
  const out: string[] = [];
  const v = vm.summary.violations === "unknown" ? (lang === "zh" ? "未知" : "unknown") : String(vm.summary.violations);
  if (lang === "zh") {
    out.push(`技能 ${vm.summary.skills} · 违规 ${v} · hub 行数 ${vm.summary.hubLines}`);
  } else {
    out.push(`${vm.summary.skills} skills · ${v} violations · ${vm.summary.hubLines} hub lines`);
  }
  out.push("");
  for (const g of vm.groups) {
    const lbl = GROUP_LABEL[g.key];
    const total = g.rows.reduce((acc, r) => acc + r.usage, 0);
    out.push(
      lang === "zh"
        ? `${lbl.zh}（${g.rows.length} 个技能 · ${total} 次调用）`
        : `${lbl.en} (${g.rows.length} skills · ${total} invocations)`,
    );
    for (const r of g.rows) {
      const usageTxt = r.usage > 0 ? `×${r.usage}` : "—";
      const status = !r.auditKnown
        ? lang === "zh" ? "未知" : "unknown"
        : r.violations.length === 0
          ? "ok"
          : r.violations.join(", ");
      out.push(`  ${r.name}  ${usageTxt}  ${status}`);
    }
  }
  return out.join("\n") + "\n";
}

export function skillsCommand(args: string[]): number {
  const sub = args[0] ?? "";
  const lang = msgLang();

  // AC6: `--json` is honored ONLY by `audit`. On any other subcommand it must
  // fail loud (clear message, exit non-zero) — never silently print the human
  // view or empty JSON. This guard fires BEFORE the generate/check/sync paths so
  // they cannot quietly ignore the flag.
  if (args.includes("--json") && sub !== "audit") {
    err(
      lang === "zh"
        ? `'roll skills ${sub === "" ? "(无子命令)" : sub}' 不支持 --json（仅 audit 支持）`
        : `'roll skills ${sub === "" ? "(no subcommand)" : sub}' does not support --json (only audit does)`,
    );
    return 1;
  }

  if (sub === "generate" || sub === "gen") {
    if (isInstallTree()) {
      installSkipNotice();
      return 0;
    }
    const target = catalogPath();
    writeFileSync(target, generateCatalog());
    info(t(v2Catalog, lang, "skills.generated", target));
    return 0;
  }

  if (sub === "check") {
    const target = catalogPath();
    if (!existsSync(target)) {
      err(t(v2Catalog, lang, "skills.check_missing", target));
      return 1;
    }
    // Generate once into a temp file so the verdict and the printed diff are
    // computed against identical content (mirrors the bash fresh-tmp dance).
    const fresh = join(mkdtempSync(join(tmpdir(), "roll-skills-")), "skills.md");
    writeFileSync(fresh, generateCatalog());
    // Capture `diff -u`'s stdout once: empty (exit 0) ⇒ identical; non-empty
    // (exit 1) ⇒ drift, and the captured bytes ARE the oracle's diff output.
    let diffOut = "";
    let identical = true;
    try {
      execFileSync("diff", ["-u", target, fresh], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    } catch (e) {
      identical = false;
      diffOut = (e as { stdout?: string }).stdout ?? "";
    }
    if (identical) {
      info(t(v2Catalog, lang, "skills.check_ok"));
      return 0;
    }
    err(t(v2Catalog, lang, "skills.check_drift", target));
    // Write the diff through process.stdout (capturable + byte-identical to the
    // oracle's `diff -u` body; the `---`/`+++` header is diff's own bytes).
    process.stdout.write(diffOut);
    return 1;
  }

  if (sub === "sync") {
    // The install/sync action (AC1): write the projected catalog to
    // guide/skills.md — the SAME write `roll setup skills` (generate) performs.
    // On an install tree there is no source to maintain → skip (exit 0).
    if (isInstallTree()) {
      installSkipNotice();
      return 0;
    }
    const target = catalogPath();
    writeFileSync(target, generateCatalog());
    if (lang === "zh") {
      info(`已同步技能目录：${target}`);
    } else {
      info(`Synced skill catalog: ${target}`);
    }
    return 0;
  }

  if (sub === "audit") {
    // US-DOSSIER-032: the ONE audit yardstick (skills-audit.ts), the SAME the
    // Skills page and scripts/audit-skills.mjs consume. US-DOSSIER-036: the
    // audit reports skills · violations · hub lines + the four invocation groups
    // (delivery/quality/observe/lifecycle) via collectSkillsPanel — the SAME
    // panel VM the web Skills page renders, so the numbers match (AC1/AC7).
    // --json emits that VM; --strict gates on violations (exit 1).
    const rest = args.slice(1);
    const json = rest.includes("--json");
    const strict = rest.includes("--strict");
    const vm = collectSkillsPanel(projectRoot());
    if (json) process.stdout.write(JSON.stringify(vm, null, 2) + "\n");
    else process.stdout.write(renderAuditPanel(vm, lang));
    const violations = vm.summary.violations === "unknown" ? 0 : vm.summary.violations;
    return strict && violations > 0 ? 1 : 0;
  }

  if (sub === "" || sub === "help" || sub === "-h" || sub === "--help") {
    process.stdout.write(skillsUsage(lang));
    return 0;
  }

  err(t(v2Catalog, lang, "skills.unknown_sub", sub));
  process.stdout.write(skillsUsage(lang));
  return 1;
}

/** Bilingual usage (AC1/AC8): audit · sync surfaced alongside the legacy nests,
 *  EN and 中 on SEPARATE lines, never inline. */
function skillsUsage(lang: Lang): string {
  if (lang === "zh") {
    return [
      "用法：roll skills <audit|sync>",
      "  audit [--strict] [--json]   严格审计技能（技能·违规·hub 行数 + 四组调用频次）",
      "  sync                        同步技能目录到 guide/skills.md",
      "  （doctor skills 体检 · setup skills 安装仍可用）",
    ].join("\n") + "\n";
  }
  return [
    "Usage: roll skills <audit|sync>",
    "  audit [--strict] [--json]   Strict skills audit (skills · violations · hub lines + 4 invocation groups)",
    "  sync                        Sync the skill catalog to guide/skills.md",
    "  (roll doctor skills checks · roll setup skills installs still work)",
  ].join("\n") + "\n";
}
