/**
 * Unit tests: sentinel remote status-push decision (US-LOOP-008).
 *
 * Pins the cadence (which terminals push), the three skip gates, the 60s
 * watchdog deadline, and the 1MB-rotate-keep-2 log policy against the bin/roll
 * oracle line ranges cited in sentinel.ts. The snapshot CONTENT shape is
 * generated by roll-meta's ops/push-loop-status.sh (not in this checkout) and is
 * out of scope — documented in the module header.
 */
import { describe, expect, it } from "vitest";
import {
  type LoopTerminal,
  type SentinelConfig,
  PUSH_LOG_ROTATE_BYTES,
  PUSH_WATCHDOG_SEC,
  logRotationPlan,
  statusPushPlan,
  terminalPushes,
} from "../src/index.js";

const ok: SentinelConfig = { rollMetaDir: "/home/u/roll-meta", metaDirExists: true, pushScriptExists: true };

describe("terminalPushes — cadence (bin/roll 9202 idle / 9270 done)", () => {
  it("idle and done push (F4 freshness heartbeat)", () => {
    expect(terminalPushes("idle")).toBe(true);
    expect(terminalPushes("done")).toBe(true);
  });
  it("failed / aborted / blocked do NOT push (no call site)", () => {
    for (const t of ["failed", "aborted", "blocked"] as LoopTerminal[]) {
      expect(terminalPushes(t)).toBe(false);
    }
  });
});

describe("statusPushPlan — skip-gate ladder (bin/roll 8102-8113)", () => {
  it("idle + fully configured → push with script path + 60s watchdog", () => {
    const plan = statusPushPlan("idle", ok);
    expect(plan).toEqual({
      action: "push",
      metaDir: "/home/u/roll-meta",
      scriptPath: "/home/u/roll-meta/ops/push-loop-status.sh",
      watchdogSec: PUSH_WATCHDOG_SEC,
    });
  });

  it("done path pushes too (bin/roll 9270)", () => {
    expect(statusPushPlan("done", ok).action).toBe("push");
  });

  it("trailing slash on metaDir is normalized in scriptPath", () => {
    const plan = statusPushPlan("idle", { ...ok, rollMetaDir: "/home/u/roll-meta/" });
    expect(plan).toMatchObject({ action: "push", scriptPath: "/home/u/roll-meta/ops/push-loop-status.sh" });
  });

  it("non-pushing terminal → skip terminal_not_pushed (no warn)", () => {
    expect(statusPushPlan("failed", ok)).toEqual({ action: "skip", reason: "terminal_not_pushed", warn: false, warning: "" });
  });

  it("unconfigured roll_meta_dir → skip unconfigured, ZERO output (8104-8105)", () => {
    expect(statusPushPlan("idle", { rollMetaDir: undefined, metaDirExists: false, pushScriptExists: false })).toEqual({
      action: "skip",
      reason: "unconfigured",
      warn: false,
      warning: "",
    });
    expect(statusPushPlan("idle", { rollMetaDir: "", metaDirExists: false, pushScriptExists: false }).reason).toBe("unconfigured");
  });

  it("configured but dir missing → skip meta_dir_missing with WARNING (8106-8108)", () => {
    const plan = statusPushPlan("idle", { rollMetaDir: "/no/such", metaDirExists: false, pushScriptExists: false });
    expect(plan).toEqual({
      action: "skip",
      reason: "meta_dir_missing",
      warn: true,
      warning: "WARNING: roll_meta_dir '/no/such' does not exist; skipping status push",
    });
  });

  it("dir exists but push script absent → silent skip (8111-8113)", () => {
    expect(statusPushPlan("idle", { ...ok, pushScriptExists: false })).toEqual({
      action: "skip",
      reason: "push_script_missing",
      warn: false,
      warning: "",
    });
  });
});

describe("logRotationPlan — 1MB rotate keep 2 (bin/roll 8117-8125)", () => {
  it("under threshold → no rotation", () => {
    expect(logRotationPlan("/l/push.log", PUSH_LOG_ROTATE_BYTES, true)).toEqual({ rotate: false, remove: [], renames: [], touch: undefined });
  });

  it("at exactly 1MiB → no rotation (strict `-gt`)", () => {
    expect(logRotationPlan("/l/push.log", 1_048_576, false).rotate).toBe(false);
  });

  it("over threshold with .1 present → drop .2, .1→.2, base→.1, touch (8121-8124)", () => {
    const plan = logRotationPlan("/l/push.log", PUSH_LOG_ROTATE_BYTES + 1, true);
    expect(plan).toEqual({
      rotate: true,
      remove: ["/l/push.log.2"],
      renames: [
        { from: "/l/push.log.1", to: "/l/push.log.2" },
        { from: "/l/push.log", to: "/l/push.log.1" },
      ],
      touch: "/l/push.log",
    });
  });

  it("over threshold WITHOUT .1 → only base→.1 rename (8122 guard)", () => {
    const plan = logRotationPlan("/l/push.log", PUSH_LOG_ROTATE_BYTES + 1, false);
    expect(plan.renames).toEqual([{ from: "/l/push.log", to: "/l/push.log.1" }]);
    expect(plan.remove).toEqual(["/l/push.log.2"]);
  });
});

describe("statusPushPlan drives a transport contract (no spawn)", () => {
  it("a fake transport receives the exact plan params", () => {
    const calls: Array<[string, string, string, number]> = [];
    const transport = {
      push(scriptPath: string, metaDir: string, logPath: string, watchdogSec: number): void {
        calls.push([scriptPath, metaDir, logPath, watchdogSec]);
      },
    };
    const plan = statusPushPlan("idle", ok);
    if (plan.action === "push") {
      transport.push(plan.scriptPath, plan.metaDir, "/l/push.log", plan.watchdogSec);
    }
    expect(calls).toEqual([["/home/u/roll-meta/ops/push-loop-status.sh", "/home/u/roll-meta", "/l/push.log", 60]]);
  });
});
