import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { type InitFacts, type InitProjectKind } from "./init-diagnosis.js";

export interface InitBriefResult {
  relPath: ".roll/brief.md";
  created: boolean;
  nextCommand: string;
  sourcePath?: string;
}

const MAX_SOURCE_BYTES = 24_000;

function firstBriefSource(facts: InitFacts): string | undefined {
  return facts.docs.prdFiles[0] ?? facts.docs.extractedSignals[0] ?? facts.docs.designDocs[0] ?? facts.docs.readmeFiles[0];
}

function readSourceExcerpt(projectDir: string, rel: string): string {
  const path = join(projectDir, rel);
  try {
    const st = statSync(path);
    if (!st.isFile() || st.size <= 0) return "";
    const text = readFileSync(path, "utf8").slice(0, MAX_SOURCE_BYTES);
    return text.trim();
  } catch {
    return "";
  }
}

function renderPrdBrief(projectDir: string, sourcePath: string): string {
  const excerpt = readSourceExcerpt(projectDir, sourcePath);
  return [
    "# Project Brief",
    "",
    "Generated by `roll init` from a detected product/requirements document.",
    "",
    "## Source",
    "",
    `- ${sourcePath}`,
    "",
    "## Starting Point",
    "",
    excerpt === "" ? "_The source document could not be read; add the product brief here before running `roll design`._" : excerpt,
    "",
  ].join("\n");
}

function renderEmptyBrief(): string {
  return [
    "# Project Brief",
    "",
    "Generated by `roll init --auto` for an empty workspace.",
    "",
    "## What are we building?",
    "",
    "TODO: Describe the product, users, and first useful outcome before running `roll design`.",
    "",
  ].join("\n");
}

export function initDesignNextCommand(kind: InitProjectKind, facts: InitFacts): string {
  if (kind === "prd-only") {
    const sourcePath = firstBriefSource(facts);
    if (sourcePath !== undefined && sourcePath !== "") return `roll design --from-file ${sourcePath}`;
  }
  return "roll design";
}

export function writeInitBrief(projectDir: string, kind: InitProjectKind, facts: InitFacts): InitBriefResult | null {
  if (kind !== "prd-only" && kind !== "empty") return null;
  const briefPath = join(projectDir, ".roll", "brief.md");
  const sourcePath = kind === "prd-only" ? firstBriefSource(facts) : undefined;
  const result: InitBriefResult = {
    relPath: ".roll/brief.md",
    created: !existsSync(briefPath),
    nextCommand: initDesignNextCommand(kind, facts),
    ...(sourcePath !== undefined ? { sourcePath } : {}),
  };
  if (!result.created) return result;

  mkdirSync(dirname(briefPath), { recursive: true });
  writeFileSync(briefPath, sourcePath !== undefined ? renderPrdBrief(projectDir, sourcePath) : renderEmptyBrief());
  return result;
}
