/**
 * US-DOSSIER-001c — the story dossier page
 * (`.roll/features/<epic>/<ID>/index.html`, regenerated by `roll index`).
 *
 * One story, five stations: Definition (the wish, quoted from spec.md) →
 * Design (spec bullets) → Execution (TCR commits, when the caller supplies
 * them) → Delivery (attest banner + AC table from ac-map.json) →
 * Retrospective (self-score note). Every figure on the page is computed from
 * the real card folder — spec.md / ac-map.json / latest/ — never typed in.
 *
 * Coexistence with story-page.ts: renderStoryPage() mints the INITIAL
 * skeleton when a card is born (roll idea / migrate) and markPhaseDone()
 * advances it mid-flight; this renderer REBUILDS the page from data when
 * `roll index` sweeps. Both wear the same chrome; the dossier is the
 * data-complete form.
 */
import { CHROME_CONTROLS, CHROME_CSS, CHROME_SCRIPT, bi } from "@roll/core";
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join as joinPath } from "node:path";
import { type DossierStory } from "./archive.js";
import { DOSSIER_CSS } from "./dossier-css.js";
import { SPINE_STAGES } from "./dossier-index.js";

const esc = (s: string): string =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** One AC row as read from ac-map.json (001d wires the file in). */
export interface AcRow {
  ac: string;
  status: string;
  note?: string;
}

/** Everything the dossier needs beyond the 001a story model. */
export interface StoryDossierInput {
  story: DossierStory;
  /** The story primitive parsed from spec.md (US-DOSSIER-003). */
  narrative?: { asA?: string; iWant?: string; soThat?: string };
  /** Domain Model Context line, e.g. "Acceptance Evidence" (US-DOSSIER-003). */
  context?: string;
  /** AC checklist items parsed from the spec's `**AC:**` block (US-DOSSIER-003). */
  acItems?: { text: string; checked: boolean }[];
  /** First blockquote / lede paragraph of spec.md — the wish (fallback). */
  wish?: string;
  /** Spec bullets under a 方案/Solution/Design heading. */
  design?: string[];
  /** TCR commit subjects touching this story (oldest first). */
  commits?: string[];
  /** Parsed ac-map.json rows. */
  acRows?: AcRow[];
  /** Relative href to the attest report (when latest/ carries one). */
  reportHref?: string;
  /** Retrospective text (self-score note body). */
  retro?: string;
}

/** Which stations are complete, derived from the data we actually have. */
export function stationsDone(d: StoryDossierInput): Set<string> {
  const done = new Set<string>(["definition"]); // a card existing IS the definition
  if ((d.design?.length ?? 0) > 0) done.add("design");
  if ((d.commits?.length ?? 0) > 0) done.add("execution");
  if (d.story.delivered) done.add("delivery");
  if (d.retro !== undefined && d.retro !== "") done.add("retrospective");
  return done;
}

/** The full spine for this story — done stations filled, delivery in truth-green. */
export function storySpine(d: StoryDossierInput): string {
  const done = stationsDone(d);
  const nodes = SPINE_STAGES.map((s, i) => {
    const cls = done.has(s.key) ? (s.key === "delivery" ? " truth" : " done") : "";
    const segDone = done.has(s.key) && i < SPINE_STAGES.length - 1 && done.has(SPINE_STAGES[i + 1]!.key);
    const seg = i < SPINE_STAGES.length - 1 ? `<span class="seg${segDone ? " done" : ""}"></span>` : "";
    return `<span class="node${cls}"><span class="dot"></span><span class="tag">${bi(s.en, s.zh)}</span></span>${seg}`;
  });
  return `<div class="spine">${nodes.join("")}</div>`;
}

const AC_BADGE: Record<string, [string, string]> = {
  pass: ["✓ pass", "✓ 通过"],
  readonly: ["◆ readonly", "◆ 只读"],
  partial: ["◑ partial", "◑ 部分"],
  fail: ["✗ fail", "✗ 失败"],
  blocked: ["■ blocked", "■ 受阻"],
  claimed: ["△ claimed", "△ 仅声称"],
  missing: ["○ missing", "○ 缺失"],
};

function section(en: string, zh: string, body: string, empty: boolean): string {
  return (
    `<section class="phase ${empty ? "phase-pending" : "phase-done"}">` +
    `<h2>${bi(en, zh)}</h2>${body}</section>`
  );
}

/** Render the dossier page. */
export function renderStoryDossier(d: StoryDossierInput): string {
  const s = d.story;
  // US-DOSSIER-003: definition station = story primitive (As a / I want / So
  // that). Falls back to the wish blockquote, then an honest empty state.
  const n = d.narrative;
  const hasNarr = n !== undefined && (n.asA !== undefined || n.iWant !== undefined || n.soThat !== undefined);
  const narrRow = (label: [string, string], v: string | undefined): string =>
    v === undefined || v === "" ? "" : `<div class="np-row"><dt>${bi(label[0], label[1])}</dt><dd>${esc(v)}</dd></div>`;
  const definition = hasNarr
    ? `<dl class="story-primitive">` +
      narrRow(["As a", "作为"], n?.asA) +
      narrRow(["I want", "我要"], n?.iWant) +
      narrRow(["So that", "以便"], n?.soThat) +
      `</dl>`
    : d.wish !== undefined && d.wish !== ""
      ? `<div class="wish-quote">${esc(d.wish)}</div>`
      : `<p class="empty">${bi("No story primitive in spec.md", "spec.md 未记录故事原语")}</p>`;
  const defEmpty = !hasNarr && (d.wish === undefined || d.wish === "");
  // US-DOSSIER-003: AC checklist (the definition of done) rendered inline.
  const acChecklist =
    (d.acItems?.length ?? 0) > 0
      ? `<ul class="ac-checklist">${(d.acItems ?? [])
          .map((a) => `<li>${a.checked ? "☑" : "☐"} ${esc(a.text)}</li>`)
          .join("")}</ul>`
      : `<p class="empty">${bi("No AC in spec.md", "spec.md 未记录 AC")}</p>`;
  const design =
    (d.design?.length ?? 0) > 0
      ? `<ul>${(d.design ?? []).map((b) => `<li>${esc(b)}</li>`).join("")}</ul>`
      : `<p class="empty">${bi("Not yet designed", "尚未设计")}</p>`;
  const execution =
    (d.commits?.length ?? 0) > 0
      ? `<p>${bi(`${(d.commits ?? []).length} TCR commits`, `${(d.commits ?? []).length} 个 TCR 提交`)}</p>` +
        `<ul class="muted">${(d.commits ?? []).map((c) => `<li><code>${esc(c)}</code></li>`).join("")}</ul>`
      : `<p class="empty">${bi("No cycles yet", "暂无周期")}</p>`;
  const banner = s.delivered
    ? `<div class="attest-banner"><span class="mark">✓</span><div>` +
      `${bi("Merged to main — attested", "已合主干 · 已验收")}` +
      (d.reportHref !== undefined ? ` · <a href="${esc(d.reportHref)}">${bi("Attestation report", "验收报告")}</a>` : "") +
      `</div></div>`
    : "";
  const acTable =
    (d.acRows?.length ?? 0) > 0
      ? `<table class="ac-table"><thead><tr><th>AC</th><th>${bi("Status", "状态")}</th><th>${bi("Note", "备注")}</th></tr></thead><tbody>` +
        (d.acRows ?? [])
          .map((r) => {
            const [en, zh] = AC_BADGE[r.status] ?? [r.status, r.status];
            return `<tr><td><code>${esc(r.ac)}</code></td><td>${bi(en, zh)}</td><td>${esc(r.note ?? "")}</td></tr>`;
          })
          .join("") +
        `</tbody></table>`
      : "";
  const delivery =
    s.delivered || (d.acRows?.length ?? 0) > 0
      ? banner + acTable
      : `<p class="empty">${bi("Not yet delivered", "尚未交付")}</p>`;
  const retro =
    d.retro !== undefined && d.retro !== ""
      ? `<p>${esc(d.retro)}</p>`
      : `<p class="empty">${bi("Not yet written", "尚未撰写")}</p>`;

  return (
    `<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="UTF-8">\n` +
    `<meta name="viewport" content="width=device-width, initial-scale=1">\n` +
    `<title>${esc(s.id)}${s.title !== undefined ? ` — ${esc(s.title)}` : ""}</title>\n` +
    `<style>\n${CHROME_CSS}${DOSSIER_CSS}` +
    `.phase-done { border-left:4px solid var(--pass); } .phase-pending { border-left:4px solid var(--line); }\n` +
    `.story-primitive { margin:0; } .story-primitive .np-row { display:flex; gap:10px; margin:4px 0; }\n` +
    `.story-primitive dt { flex:0 0 64px; color:var(--muted); font:600 12.5px/1.7 var(--sans); }\n` +
    `.story-primitive dd { margin:0; flex:1; }\n` +
    `.ac-checklist { list-style:none; padding:0; margin:0; } .ac-checklist li { margin:3px 0; }\n` +
    `</style>\n${CHROME_SCRIPT}\n</head>\n<body>\n${CHROME_CONTROLS}\n` +
    `<div class="masthead">\n` +
    `<p class="crumb"><a href="../../index.html">${bi("Features Index", "功能档案")}</a> / <a href="../index.html">${esc(s.epic)}</a> / ${esc(s.id)}</p>\n` +
    `<p class="kicker">Roll · ${bi("Story Dossier", "故事档案")}</p>\n` +
    `<h1><code>${esc(s.id)}</code></h1>\n` +
    (s.title !== undefined ? `<p class="lede">${esc(s.title)}</p>\n` : "") +
    `<div class="kv"><span class="type type-${esc(s.type)}">${esc(s.type)}</span>` +
    `<span>${bi("epic", "史诗")} <b>${esc(s.epic)}</b></span>` +
    (d.context !== undefined && d.context !== "" ? `<span>${bi("context", "上下文")} <b>${esc(d.context)}</b></span>` : "") +
    (s.created !== undefined ? `<span>${bi("created", "创建")} <b>${esc(s.created)}</b></span>` : "") +
    `<span><a href="spec.md">${bi("Design doc · spec.md", "设计文档 · spec.md")}</a></span>` +
    `</div>\n</div>\n` +
    storySpine(d) +
    section("Definition", "立项", definition, defEmpty) +
    section("Acceptance Criteria", "验收标准", acChecklist, (d.acItems?.length ?? 0) === 0) +
    section("Design", "设计", design, (d.design?.length ?? 0) === 0) +
    section("Execution", "执行", execution, (d.commits?.length ?? 0) === 0) +
    section("Delivery", "交付", delivery, !(s.delivered || (d.acRows?.length ?? 0) > 0)) +
    section("Retrospective", "复盘", retro, d.retro === undefined || d.retro === "") +
    `<footer>Roll · <a href="spec.md">spec.md</a></footer>\n</body>\n</html>\n`
  );
}

// ── US-DOSSIER-001d — fill the dossier input from the real card folder ──────

/**
 * Read everything renderStoryDossier needs from the card folder + repo:
 * spec.md (wish = first blockquote; design = bullets under a 方案/Solution/
 * Design heading), ac-map.json, the latest/ report, the newest self-score
 * note, and the story's `tcr:` commits from git history. Every read is
 * best-effort — a missing source renders as an honest empty state.
 */
export function collectStoryDossierInput(projectPath: string, story: DossierStory): StoryDossierInput {
  const dir = joinPath(projectPath, ".roll", "features", story.epic, story.id);
  const out: StoryDossierInput = { story };

  // spec.md → wish + design bullets.
  try {
    const spec = readFile(joinPath(dir, "spec.md"));
    const quote: string[] = [];
    for (const l of spec.split("\n")) {
      const m = /^>\s?(.*)$/.exec(l);
      if (m !== null) quote.push((m[1] ?? "").trim());
      else if (quote.length > 0) break;
    }
    const wish = quote.join(" ").replace(/\s+/g, " ").trim();
    if (wish !== "") out.wish = wish;
    // US-DOSSIER-003: story primitive (As a / I want / So that).
    const narr: { asA?: string; iWant?: string; soThat?: string } = {};
    const asA = /^[-*]\s*As a\s+(.*)$/im.exec(spec);
    const iWant = /^[-*]\s*I want\s+(.*)$/im.exec(spec);
    const soThat = /^[-*]\s*So that\s+(.*)$/im.exec(spec);
    if (asA !== null) narr.asA = (asA[1] ?? "").trim();
    if (iWant !== null) narr.iWant = (iWant[1] ?? "").trim();
    if (soThat !== null) narr.soThat = (soThat[1] ?? "").trim();
    if (narr.asA !== undefined || narr.iWant !== undefined || narr.soThat !== undefined) out.narrative = narr;
    // US-DOSSIER-003: Domain Model Context line.
    const ctx = /^[-*]\s*Context:\s*(.*)$/im.exec(spec);
    if (ctx !== null) out.context = (ctx[1] ?? "").trim();
    // US-DOSSIER-003: AC checklist (the `**AC:**` block's checkbox items).
    const acItems: { text: string; checked: boolean }[] = [];
    let inAc = false;
    for (const l of spec.split("\n")) {
      if (/^\*\*AC:?\*\*/i.test(l.trim())) { inAc = true; continue; }
      if (inAc && /^\*\*[A-Z]/.test(l.trim())) break; // next bold section ends the block
      const m = /^[-*]\s*\[([ xX])\]\s+(.*)$/.exec(l.trim());
      if (inAc && m !== null) acItems.push({ checked: (m[1] ?? "").toLowerCase() === "x", text: (m[2] ?? "").trim() });
    }
    if (acItems.length > 0) out.acItems = acItems;
    const design: string[] = [];
    let inDesign = false;
    for (const l of spec.split("\n")) {
      if (/^#{2,3}\s*(方案|Solution|Design)/i.test(l)) inDesign = true;
      else if (/^#{1,3}\s/.test(l)) inDesign = false;
      else if (inDesign) {
        const m = /^[-*]\s+(.*)$/.exec(l.trim());
        if (m !== null) design.push((m[1] ?? "").trim());
      }
    }
    if (design.length > 0) out.design = design;
  } catch {
    /* no spec — bare card */
  }

  // ac-map.json → AC rows.
  try {
    const rows = JSON.parse(readFile(joinPath(dir, "ac-map.json"))) as Array<{
      ac?: string;
      status?: string;
      note?: string;
    }>;
    if (Array.isArray(rows)) {
      const acRows = rows
        .filter((r) => typeof r.ac === "string" && typeof r.status === "string")
        .map((r) => ({ ac: r.ac as string, status: r.status as string, ...(r.note !== undefined ? { note: r.note } : {}) }));
      if (acRows.length > 0) out.acRows = acRows;
    }
  } catch {
    /* no ac-map yet */
  }

  // latest/<ID>-report.html → banner link.
  try {
    if (statDir(joinPath(dir, "latest", `${story.id}-report.html`))) out.reportHref = `latest/${story.id}-report.html`;
  } catch {
    /* no report */
  }

  // newest self-score note → retrospective line. Card-local notes/ is the
  // home (US-META-008); the flat .roll/notes serves pre-migration history.
  try {
    const cardNotes = joinPath(dir, "notes");
    const legacyNotes = joinPath(projectPath, ".roll", "notes");
    let notesDir = cardNotes;
    let notes: string[] = [];
    try {
      notes = listDir(cardNotes).filter((f) => f.endsWith(".md")).sort();
    } catch {
      /* no card-local notes yet */
    }
    if (notes.length === 0) {
      notesDir = legacyNotes;
      notes = listDir(legacyNotes)
        .filter((f) => f.includes(`-${story.id}-`) && f.endsWith(".md"))
        .sort();
    }
    const last = notes[notes.length - 1];
    if (last !== undefined) {
      const body = readFile(joinPath(notesDir, last));
      const score = /^score:\s*(.+)$/m.exec(body);
      const verdict = /^verdict:\s*(.+)$/m.exec(body);
      const para = body
        .split(/\n{2,}/)
        .map((p) => p.trim())
        .find((p) => p !== "" && !p.startsWith("---") && !/^score:|^verdict:/m.test(p));
      out.retro = [
        score !== null ? `score ${(score[1] ?? "").trim()}` : "",
        verdict !== null ? `· ${(verdict[1] ?? "").trim()}` : "",
        para !== undefined ? `— ${para.replace(/\s+/g, " ").slice(0, 240)}` : "",
      ]
        .join(" ")
        .trim();
    }
  } catch {
    /* no notes */
  }

  // git history → tcr commits mentioning the story (oldest first).
  try {
    const log = execGit(projectPath, ["log", "--format=%s", "--fixed-strings", "--grep", story.id, "--reverse"]);
    const commits = log
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l !== "")
      .slice(0, 40);
    if (commits.length > 0) out.commits = commits;
  } catch {
    /* not a git repo / git unavailable */
  }

  return out;
}

// Thin fs/git seams (kept local so the renderer stays pure above).
function readFile(p: string): string {
  return readFileSync(p, "utf8");
}
function listDir(p: string): string[] {
  return readdirSync(p);
}
function statDir(p: string): boolean {
  return statSync(p).isFile();
}
function execGit(cwd: string, args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf8", timeout: 10_000 });
}
