/**
 * US-DOSSIER-001c — the story dossier page
 * (`.roll/features/<epic>/<ID>/index.html`, regenerated by `roll index`).
 *
 * One story, five stations: Definition (the wish, quoted from spec.md) →
 * Design (spec bullets) → Execution (TCR commits, when the caller supplies
 * them) → Delivery (attest banner + AC table from ac-map.json) →
 * Retrospective (self-score note). Every figure on the page is computed from
 * the real card folder — spec.md / ac-map.json / latest/ — never typed in.
 *
 * Coexistence with story-page.ts: renderStoryPage() mints the INITIAL
 * skeleton when a card is born (roll idea / migrate) and markPhaseDone()
 * advances it mid-flight; this renderer REBUILDS the page from data when
 * `roll index` sweeps. Both wear the same chrome; the dossier is the
 * data-complete form.
 */
import { CHROME_CONTROLS, CHROME_CSS, CHROME_SCRIPT, bi } from "@roll/core";
import { type DossierStory } from "./archive.js";
import { DOSSIER_CSS } from "./dossier-css.js";
import { SPINE_STAGES } from "./dossier-index.js";

const esc = (s: string): string =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** One AC row as read from ac-map.json (001d wires the file in). */
export interface AcRow {
  ac: string;
  status: string;
  note?: string;
}

/** Everything the dossier needs beyond the 001a story model. */
export interface StoryDossierInput {
  story: DossierStory;
  /** First blockquote / lede paragraph of spec.md — the wish. */
  wish?: string;
  /** Spec bullets under a 方案/Solution/Design heading. */
  design?: string[];
  /** TCR commit subjects touching this story (oldest first). */
  commits?: string[];
  /** Parsed ac-map.json rows. */
  acRows?: AcRow[];
  /** Relative href to the attest report (when latest/ carries one). */
  reportHref?: string;
  /** Retrospective text (self-score note body). */
  retro?: string;
}

/** Which stations are complete, derived from the data we actually have. */
export function stationsDone(d: StoryDossierInput): Set<string> {
  const done = new Set<string>(["definition"]); // a card existing IS the definition
  if ((d.design?.length ?? 0) > 0) done.add("design");
  if ((d.commits?.length ?? 0) > 0) done.add("execution");
  if (d.story.delivered) done.add("delivery");
  if (d.retro !== undefined && d.retro !== "") done.add("retrospective");
  return done;
}

/** The full spine for this story — done stations filled, delivery in truth-green. */
export function storySpine(d: StoryDossierInput): string {
  const done = stationsDone(d);
  const nodes = SPINE_STAGES.map((s, i) => {
    const cls = done.has(s.key) ? (s.key === "delivery" ? " truth" : " done") : "";
    const segDone = done.has(s.key) && i < SPINE_STAGES.length - 1 && done.has(SPINE_STAGES[i + 1]!.key);
    const seg = i < SPINE_STAGES.length - 1 ? `<span class="seg${segDone ? " done" : ""}"></span>` : "";
    return `<span class="node${cls}"><span class="dot"></span><span class="tag">${bi(s.en, s.zh)}</span></span>${seg}`;
  });
  return `<div class="spine">${nodes.join("")}</div>`;
}

const AC_BADGE: Record<string, [string, string]> = {
  pass: ["✓ pass", "✓ 通过"],
  readonly: ["◆ readonly", "◆ 只读"],
  partial: ["◑ partial", "◑ 部分"],
  fail: ["✗ fail", "✗ 失败"],
  blocked: ["■ blocked", "■ 受阻"],
  claimed: ["△ claimed", "△ 仅声称"],
  missing: ["○ missing", "○ 缺失"],
};

function section(en: string, zh: string, body: string, empty: boolean): string {
  return (
    `<section class="phase ${empty ? "phase-pending" : "phase-done"}">` +
    `<h2>${bi(en, zh)}</h2>${body}</section>`
  );
}

/** Render the dossier page. */
export function renderStoryDossier(d: StoryDossierInput): string {
  const s = d.story;
  const definition =
    d.wish !== undefined && d.wish !== ""
      ? `<div class="wish-quote">${esc(d.wish)}</div>`
      : `<p class="empty">${bi("No wish recorded in spec.md", "spec.md 未记录愿望")}</p>`;
  const design =
    (d.design?.length ?? 0) > 0
      ? `<ul>${(d.design ?? []).map((b) => `<li>${esc(b)}</li>`).join("")}</ul>`
      : `<p class="empty">${bi("Not yet designed", "尚未设计")}</p>`;
  const execution =
    (d.commits?.length ?? 0) > 0
      ? `<p>${bi(`${(d.commits ?? []).length} TCR commits`, `${(d.commits ?? []).length} 个 TCR 提交`)}</p>` +
        `<ul class="muted">${(d.commits ?? []).map((c) => `<li><code>${esc(c)}</code></li>`).join("")}</ul>`
      : `<p class="empty">${bi("No cycles yet", "暂无周期")}</p>`;
  const banner = s.delivered
    ? `<div class="attest-banner"><span class="mark">✓</span><div>` +
      `${bi("Merged to main — attested", "已合主干 · 已验收")}` +
      (d.reportHref !== undefined ? ` · <a href="${esc(d.reportHref)}">${bi("Attestation report", "验收报告")}</a>` : "") +
      `</div></div>`
    : "";
  const acTable =
    (d.acRows?.length ?? 0) > 0
      ? `<table class="ac-table"><thead><tr><th>AC</th><th>${bi("Status", "状态")}</th><th>${bi("Note", "备注")}</th></tr></thead><tbody>` +
        (d.acRows ?? [])
          .map((r) => {
            const [en, zh] = AC_BADGE[r.status] ?? [r.status, r.status];
            return `<tr><td><code>${esc(r.ac)}</code></td><td>${bi(en, zh)}</td><td>${esc(r.note ?? "")}</td></tr>`;
          })
          .join("") +
        `</tbody></table>`
      : "";
  const delivery =
    s.delivered || (d.acRows?.length ?? 0) > 0
      ? banner + acTable
      : `<p class="empty">${bi("Not yet delivered", "尚未交付")}</p>`;
  const retro =
    d.retro !== undefined && d.retro !== ""
      ? `<p>${esc(d.retro)}</p>`
      : `<p class="empty">${bi("Not yet written", "尚未撰写")}</p>`;

  return (
    `<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="UTF-8">\n` +
    `<meta name="viewport" content="width=device-width, initial-scale=1">\n` +
    `<title>${esc(s.id)}${s.title !== undefined ? ` — ${esc(s.title)}` : ""}</title>\n` +
    `<style>\n${CHROME_CSS}${DOSSIER_CSS}` +
    `.phase-done { border-left:4px solid var(--pass); } .phase-pending { border-left:4px solid var(--line); }\n` +
    `</style>\n${CHROME_SCRIPT}\n</head>\n<body>\n${CHROME_CONTROLS}\n` +
    `<div class="masthead">\n` +
    `<p class="crumb"><a href="../../index.html">${bi("Features Index", "功能档案")}</a> / <a href="../index.html">${esc(s.epic)}</a> / ${esc(s.id)}</p>\n` +
    `<p class="kicker">Roll · ${bi("Story Dossier", "故事档案")}</p>\n` +
    `<h1><code>${esc(s.id)}</code></h1>\n` +
    (s.title !== undefined ? `<p class="lede">${esc(s.title)}</p>\n` : "") +
    `<div class="kv"><span class="type type-${esc(s.type)}">${esc(s.type)}</span>` +
    `<span>${bi("epic", "史诗")} <b>${esc(s.epic)}</b></span>` +
    (s.created !== undefined ? `<span>${bi("created", "创建")} <b>${esc(s.created)}</b></span>` : "") +
    `</div>\n</div>\n` +
    storySpine(d) +
    section("Definition", "立项", definition, d.wish === undefined || d.wish === "") +
    section("Design", "设计", design, (d.design?.length ?? 0) === 0) +
    section("Execution", "执行", execution, (d.commits?.length ?? 0) === 0) +
    section("Delivery", "交付", delivery, !(s.delivered || (d.acRows?.length ?? 0) > 0)) +
    section("Retrospective", "复盘", retro, d.retro === undefined || d.retro === "") +
    `<footer>Roll · <a href="spec.md">spec.md</a></footer>\n</body>\n</html>\n`
  );
}
