#!/usr/bin/env bats
# US-AUTO-037: Integration tests for the per-cycle worktree lifecycle inside
# the inner runner script generated by _write_loop_runner_script.
#
# Strategy: build a tiny git fixture (bare upstream + local clone), generate
# a real inner.sh against it, drive it with a stub command that simulates
# claude's effect (e.g. `git commit --allow-empty`), then verify worktree +
# branch + main + ALERT state for happy / claude-fail / ff-fail paths.
#
# This is deliberately a unit-test-style exercise of the integration
# behaviour — exercising the OUTER runner.sh through tmux is covered by
# the existing cmd_loop.bats / roll_loop_lock.bats; this file targets the
# new worktree-orchestration logic in inner.sh.

load helpers

setup() {
  integration_setup
  # Override roll's shared dirs so they land inside TEST_TMP, not real ~/.shared
  export HOME="$TEST_TMP"
  _SHARED_ROOT="${TEST_TMP}/.shared/roll"
  _LOOP_ALERT="${_SHARED_ROOT}/loop/ALERT.md"
  mkdir -p "${_SHARED_ROOT}/loop" "${_SHARED_ROOT}/worktrees"

  # Source bin/roll to get _write_loop_runner_script + _worktree_path
  ROLL_PKG_DIR="${BATS_TEST_DIRNAME}/../.."
  export ROLL_PKG_DIR
  source "$ROLL_BIN"
  # Re-apply shared dir overrides AFTER source (which sets them from HOME at source time)
  _SHARED_ROOT="${TEST_TMP}/.shared/roll"
  _LOOP_ALERT="${_SHARED_ROOT}/loop/ALERT.md"

  # Build a tiny git fixture
  cd "$TEST_TMP"
  git -c init.defaultBranch=main init -q --bare upstream.git
  git -c init.defaultBranch=main clone -q upstream.git project
  cd project
  git config user.email "test@example.com"
  git config user.name "Test"
  git config commit.gpgsign false
  git config protocol.file.allow always
  echo "init" > README.md
  git add README.md
  git commit -q -m "initial commit"
  git push -q -u origin main

  _project="${TEST_TMP}/project"
}

teardown() {
  # Best-effort: clean up any worktree the test may have registered
  if [ -d "${_project}/.git" ]; then
    cd "$_project" 2>/dev/null \
      && git worktree list --porcelain 2>/dev/null \
      | awk '/^worktree /{print $2}' \
      | while read -r wt; do
          [ "$wt" != "$_project" ] && git worktree remove --force "$wt" 2>/dev/null || true
        done
  fi
  cd /
  integration_teardown
}

# Generate inner script for given cmd; return its path via stdout.
_make_inner() {
  local cmd="$1"
  local script="${TEST_TMP}/run-test.sh"
  _write_loop_runner_script "$script" "$_project" "$cmd" "${TEST_TMP}/log" 0 24
  echo "${script%.sh}-inner.sh"
}

# --- happy path ---

@test "worktree e2e: happy path — claude commits in worktree, merge_back ff'd to main, worktree cleaned" {
  local inner; inner=$(_make_inner 'git commit --allow-empty -m "worktree commit"')

  HOME="$TEST_TMP" bash "$inner"
  local exit_code=$?

  [ "$exit_code" -eq 0 ]

  # Main worktree has the commit
  cd "$_project"
  local main_log; main_log=$(git log --oneline -2 | head -2)
  [[ "$main_log" == *"worktree commit"* ]]

  # Origin has the commit too
  git fetch origin --quiet
  local origin_main; origin_main=$(git log origin/main --oneline -2 | head -2)
  [[ "$origin_main" == *"worktree commit"* ]]

  # Worktree dir is cleaned up
  local wt_count; wt_count=$(find "${_SHARED_ROOT}/worktrees" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
  [ "$wt_count" -eq 0 ]

  # loop/cycle-* branch is deleted
  ! git branch | grep -qF 'loop/cycle-'

  # No ALERT
  [ ! -f "$_LOOP_ALERT" ] || ! grep -qE 'failed|preserved' "$_LOOP_ALERT"
}

# --- claude failure path ---

@test "worktree e2e: claude failure — worktree preserved, ALERT written, main untouched" {
  local main_head_before; main_head_before=$(cd "$_project" && git rev-parse HEAD)

  # Stub command exits non-zero after writing a partial file to the worktree
  local inner; inner=$(_make_inner 'echo partial > work.txt && exit 1')

  HOME="$TEST_TMP" bash "$inner"
  local exit_code=$?

  # Inner runner itself exits 0 (it handles claude failure gracefully); claude's
  # non-zero exit is captured in the alert, not propagated as runner failure.
  # The for-loop retries 3 times, so the cmd runs 3x and each fails. Then alert.

  # Main has NOT advanced
  cd "$_project"
  local main_head_after; main_head_after=$(git rev-parse HEAD)
  [ "$main_head_before" = "$main_head_after" ]

  # Worktree preserved
  local wt_count; wt_count=$(find "${_SHARED_ROOT}/worktrees" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
  [ "$wt_count" -ge 1 ]

  # ALERT written
  [ -f "$_LOOP_ALERT" ]
  grep -qE 'claude exited|preserved' "$_LOOP_ALERT"
}

# --- ff-only failure path ---

@test "worktree e2e: ff-only failure (main diverged) — FIX-039 pushes orphan branch+tag, worktree cleaned, ALERT written" {
  # Plan: worktree makes commit A on loop/cycle-<id>; meanwhile main+origin
  # gets a divergent commit B. merge_back's ff-only merge fails.
  # FIX-039 then pushes the orphan branch+tag to origin as safety net and
  # cleans up the worktree — so code is never local-only.
  local inner; inner=$(_make_inner 'git commit --allow-empty -m "worktree work" && cd '"${_project}"' && git commit --allow-empty -m "divergent main work" && git push -q origin main')

  HOME="$TEST_TMP" bash "$inner"

  # FIX-039: worktree is cleaned (push to origin succeeded)
  local wt_count; wt_count=$(find "${_SHARED_ROOT}/worktrees" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
  [ "$wt_count" -eq 0 ]

  # FIX-039: orphan branch is on origin
  cd "$_project"
  git fetch origin --quiet
  git branch -r | grep -qE 'origin/loop/cycle-'

  # ALERT written — merge_back failure recorded (from _worktree_merge_back)
  [ -f "$_LOOP_ALERT" ]
  grep -qE 'merge_back failed|ff-only|merge --ff-only' "$_LOOP_ALERT"
}
