import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

const ROOT = resolve(__dirname, "../../..");
const SCRIPT = join(ROOT, "scripts/gen-module-maps.mjs");
const DOMAINS = ["attest", "reconcile", "evals", "policy"] as const;
const dirs: string[] = [];

afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

function fixtureRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "roll-module-maps-"));
  dirs.push(root);
  for (const domain of DOMAINS) {
    const dir = join(root, "packages/core/src", domain);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "sample.ts"), `/**\n * @responsibility ${domain} sample responsibility.\n */\nexport {};\n`);
  }
  return root;
}

function run(root: string): { ok: boolean; output: string } {
  try {
    return {
      ok: true,
      output: execFileSync(process.execPath, [SCRIPT, "--root", root], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }),
    };
  } catch (error) {
    const failure = error as { stdout?: Buffer | string; stderr?: Buffer | string };
    return { ok: false, output: `${failure.stdout ?? ""}${failure.stderr ?? ""}` };
  }
}

describe("US-RULE-005 — generated module maps", () => {
  it("generates stable maps from complete source declarations", () => {
    const root = fixtureRoot();

    expect(run(root)).toMatchObject({ ok: true });
    const first = readFileSync(join(root, "docs/maps/attest.md"), "utf8");
    expect(first).toContain("<!-- GENERATED by scripts/gen-module-maps.mjs; DO NOT EDIT. -->");
    expect(first).toContain("| `sample.ts` | attest sample responsibility. |");

    writeFileSync(join(root, "packages/core/src/attest/zeta.ts"), "/**\n * @responsibility zeta responsibility.\n */\nexport {};\n");
    writeFileSync(join(root, "packages/core/src/attest/alpha.ts"), "/**\n * @responsibility alpha responsibility.\n */\nexport {};\n");
    expect(run(root)).toMatchObject({ ok: true });
    const sorted = readFileSync(join(root, "docs/maps/attest.md"), "utf8");
    expect(sorted.indexOf("`alpha.ts`")).toBeLessThan(sorted.indexOf("`sample.ts`"));
    expect(sorted.indexOf("`sample.ts`")).toBeLessThan(sorted.indexOf("`zeta.ts`"));

    writeFileSync(join(root, "docs/maps/attest.md"), "hand edit\n");
    expect(run(root)).toMatchObject({ ok: true });
    expect(readFileSync(join(root, "docs/maps/attest.md"), "utf8")).toBe(sorted);
  });

  it.each([
    ["missing", "/** no declaration */\nexport {};\n", "missing @responsibility declaration"],
    ["duplicate", "/**\n * @responsibility first.\n * @responsibility second.\n */\nexport {};\n", "duplicate @responsibility declaration"],
    ["malformed", "/**\n * @responsibility\n */\nexport {};\n", "malformed @responsibility declaration"],
  ])("fails loud for a %s declaration", (_kind, source, expected) => {
    const root = fixtureRoot();
    writeFileSync(join(root, "packages/core/src/attest/sample.ts"), source);

    const result = run(root);

    expect(result.ok).toBe(false);
    expect(result.output).toContain("packages/core/src/attest/sample.ts");
    expect(result.output).toContain(expected);
  });
});
