#!/usr/bin/env bash
# Roll upstream watch — US-WATCH-001.
#
# Provides:
#   _watch_state_init        — initialize ~/.shared/roll/dream/watch-state.yaml
#   _watch_state_get <key>   — get value from watch-state.yaml by dot-path key
#   _watch_state_set <key> <val> — set value in watch-state.yaml
#   _watch_fetch_claude_releases  — fetch Claude Code GitHub releases JSON
#   _watch_get_claude_version     — get installed claude version string
#   _watch_is_evaluated <cli> <version> <entry_hash> — idempotency check
#   _watch_mark_evaluated <cli> <version> <entry_hash> — record evaluation
#   _watch_dimensions_file   — path to watch dimensions checklist
#
# All functions are lenient: network/API failures return empty output and exit 0,
# so the caller (dream) can skip Scan 7 without blocking other scans.

# --- paths -----------------------------------------------------------

WATCH_STATE_DIR="${ROLL_HOME:-${HOME}/.roll}/dream"
WATCH_STATE_FILE="${WATCH_STATE_DIR}/watch-state.yaml"

_watch_dimensions_file() {
  # Return the path to the dimensions checklist shipped with the package.
  echo "${ROLL_PKG_DIR}/lib/watch-dimensions.md"
}

# --- state management ------------------------------------------------

_watch_state_init() {
  mkdir -p "$WATCH_STATE_DIR" 2>/dev/null || true
  if [[ ! -f "$WATCH_STATE_FILE" ]]; then
    cat > "$WATCH_STATE_FILE" <<'EOF'
# Upstream watch state — auto-generated by roll dream Scan 7.
# Do not edit manually; use roll dream watch-replay for backfill.
last_scan: ""
targets: {}
evaluated: {}
EOF
  fi
}

_watch_state_get() {
  # Read a dot-path key from watch-state.yaml using simple grep+awk.
  # Keys like: last_scan, targets.claude.last_seen_version
  # Returns empty string if key not found.
  local key="$1" part rest section
  _watch_state_init  # ensure file exists
  IFS='.' read -r part rest <<< "$key"
  if [[ -z "$rest" ]]; then
    # Top-level key: "last_scan"
    awk -v k="$part" '$1 == k ":" { $1=""; sub(/^ /,""); print }' "$WATCH_STATE_FILE"
  else
    # Nested: find the section, then the sub-key
    # Simple approach: for targets.<cli>.<field>
    local cli
    IFS='.' read -r _ cli part <<< "$key"
    # Walk into targets: <cli>: block
    awk -v cli="$cli" -v field="$part" '
      $0 ~ "^  " cli ":" { in_block=1; next }
      in_block && $0 ~ "^    " field ":" { $1=""; sub(/^ /,""); print; exit }
      in_block && $0 ~ "^  [a-z]" { exit }
    ' "$WATCH_STATE_FILE"
  fi
}

_watch_state_set() {
  # Set a dot-path key in watch-state.yaml. Creates file if needed.
  # Supports: last_scan, targets.<cli>.<field>
  local key="$1" val="$2"
  _watch_state_init
  local tmp="${WATCH_STATE_FILE}.tmp.$$"
  local IFS='.' tok1 tok2 tok3
  read -r tok1 tok2 tok3 <<< "$key"

  if [[ -z "$tok3" ]]; then
    # Top-level key
    if grep -q "^${tok1}:" "$WATCH_STATE_FILE" 2>/dev/null; then
      sed "s/^${tok1}:.*/${tok1}: \"${val}\"/" "$WATCH_STATE_FILE" > "$tmp"
    else
      cp "$WATCH_STATE_FILE" "$tmp"
      echo "${tok1}: \"${val}\"" >> "$tmp"
    fi
  else
    # Nested: targets.<cli>.<field>
    local cli="$tok2" field="$tok3"
    if grep -q "^  ${cli}:" "$WATCH_STATE_FILE" 2>/dev/null; then
      # Use awk for nested field update/add (portable, no sed dialect issues)
      awk -v cli="$cli" -v field="$field" -v val="$val" '
        BEGIN { in_block=0; done=0 }
        $0 ~ "^  " cli ":" { in_block=1; print; next }
        in_block && $0 ~ "^    " field ":" { print "    " field ": \"" val "\""; done=1; next }
        in_block && $0 ~ "^  [a-z]" && !done { print "    " field ": \"" val "\""; print; done=1; in_block=0; next }
        in_block && $0 ~ "^  [a-z]" { in_block=0 }
        { print }
        END { if (in_block && !done) print "    " field ": \"" val "\"" }
      ' "$WATCH_STATE_FILE" > "$tmp"
    else
      # cli block not found — append
      cp "$WATCH_STATE_FILE" "$tmp"
      {
        echo "  ${cli}:"
        echo "    ${field}: \"${val}\""
      } >> "$tmp"
    fi
  fi
  mv "$tmp" "$WATCH_STATE_FILE"
}

# --- claude version -------------------------------------------------

_watch_get_claude_version() {
  # Get installed claude version. Falls back gracefully.
  if command -v claude &>/dev/null; then
    claude --version 2>/dev/null | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1 || true
  fi
}

# --- claude releases fetching ---------------------------------------

_watch_fetch_claude_releases() {
  # Fetch Claude Code releases from GitHub API.
  # Returns JSON array on stdout; empty on failure.
  # Caches result for 1 hour to avoid rate limiting on retries.
  local cache_file="${WATCH_STATE_DIR}/claude-releases-cache.json"
  local cache_ttl=3600

  # Return cached if fresh
  if [[ -f "$cache_file" ]]; then
    local cache_age
    cache_age=$(($(date +%s) - $(stat -f %m "$cache_file" 2>/dev/null || stat -c %Y "$cache_file" 2>/dev/null || echo 0)))
    if [[ "$cache_age" -lt "$cache_ttl" ]]; then
      cat "$cache_file"
      return 0
    fi
  fi

  # Fetch from GitHub API
  local result
  result=$(curl -sf --max-time 10 \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/repos/anthropics/claude-code/releases?per_page=5" 2>/dev/null) || true

  if [[ -n "$result" ]]; then
    echo "$result" > "$cache_file"
    echo "$result"
  elif [[ -f "$cache_file" ]]; then
    # Network failed but cache exists — return stale cache
    cat "$cache_file"
  fi
  return 0
}

# --- idempotency ----------------------------------------------------

_watch_is_evaluated() {
  # Check if (cli, version, entry_hash) has already been evaluated.
  # Returns 0 if already evaluated (skip), 1 if not (proceed).
  local cli="$1" version="$2" entry_hash="$3"
  _watch_state_init
  grep -q "${cli} ${version} ${entry_hash}" "$WATCH_STATE_FILE" 2>/dev/null
}

_watch_mark_evaluated() {
  # Record that (cli, version, entry_hash) has been evaluated.
  local cli="$1" version="$2" entry_hash="$3" tier="${4:-noise}"
  _watch_state_init
  # Append to evaluated section — simple line-based, one per entry
  if ! _watch_is_evaluated "$cli" "$version" "$entry_hash"; then
    # Remove any existing evaluated: line, then re-append
    local tmp="${WATCH_STATE_FILE}.tmp.$$"
    grep -v '^# evaluated:' "$WATCH_STATE_FILE" > "$tmp" 2>/dev/null || true
    echo "# evaluated: ${cli} ${version} ${entry_hash} ${tier} $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$tmp"
    mv "$tmp" "$WATCH_STATE_FILE"
  fi
}

# --- utility --------------------------------------------------------

_watch_next_fix_id() {
  # Determine the next FIX-XXX ID from the project's backlog.
  # Reads from the main project's backlog if ROLL_MAIN_PROJECT is set,
  # otherwise from the current directory.
  local project_dir="${ROLL_MAIN_PROJECT:-.}"
  # In test sandbox, ROLL_MAIN_PROJECT may point to real project — check cwd first
  if [[ -f "./.roll/backlog.md" ]]; then
    project_dir="."
  elif [[ ! -d "$project_dir" ]]; then
    project_dir="."
  fi
  local backlog="${project_dir}/.roll/backlog.md"
  if [[ ! -f "$backlog" ]]; then
    echo "FIX-111"
    return 0
  fi
  # Find highest FIX-NNN number
  local max_id
  max_id=$(grep -oE '\| *FIX-[0-9]+' "$backlog" 2>/dev/null | grep -oE 'FIX-[0-9]+' | sed 's/FIX-//' | sort -n | tail -1)
  if [[ -z "$max_id" ]]; then
    max_id=111  # current highest known: FIX-110
  fi
  # Force decimal to avoid octal interpretation (bash interprets 0-prefixed as octal)
  # then pad back to 3-digit format to match convention
  printf 'FIX-%03d' "$((10#${max_id} + 1))"
}
