#!/usr/bin/env bash
# Roll i18n catalog — offboard command (US-I18N-002).

_i18n_set en offboard.no_changeset_en "No onboard changeset found at .roll/onboard-changeset.yaml"
_i18n_set zh offboard.no_changeset_en "No onboard changeset found at .roll/onboard-changeset.yaml"
_i18n_set en offboard.no_changeset_zh "未找到 onboard 变更清单 .roll/onboard-changeset.yaml"
_i18n_set zh offboard.no_changeset_zh "未找到 onboard 变更清单 .roll/onboard-changeset.yaml"
_i18n_set en offboard.manual_offboard "Manual offboard — remove these by hand if they came from Roll:"
_i18n_set zh offboard.manual_offboard "手动清理——如果这些文件来自 Roll，请手动删除:"
_i18n_set en offboard.manual_rm_roll "rm -rf .roll/                  # all process artefacts"
_i18n_set zh offboard.manual_rm_roll "rm -rf .roll/                  # 所有过程文件"
_i18n_set en offboard.manual_rm_agents "rm -f AGENTS.md CLAUDE.md      # only if they were generated by roll init"
_i18n_set zh offboard.manual_rm_agents "rm -f AGENTS.md CLAUDE.md      # 仅当这些文件由 roll init 生成"
_i18n_set en offboard.manual_edit_gitignore "Edit .gitignore to remove any '.roll/' entry"
_i18n_set zh offboard.manual_edit_gitignore "编辑 .gitignore 移除 '.roll/' 条目"
