#!/usr/bin/env bash
# Roll i18n catalog — shared / common messages (US-I18N-002).
# Sourced by lib/i18n.sh. Fill with _i18n_set.

# ── update notification ──
_i18n_set en update.available "v%s available — run 'roll update' to upgrade"
_i18n_set zh update.available "有新版本 v%s — 运行 'roll update' 升级"

# ── changelog heading ──
_i18n_set en changelog.heading "Recent Changes"
_i18n_set zh changelog.heading "最近更新"

# ── init: onboard agent ──
_i18n_set en init.onboard_retry "retry the same agent:   roll init"
_i18n_set zh init.onboard_retry "再试一次同一个 agent:  roll init"
_i18n_set en init.onboard_switch "switch to another:      ROLL_ONBOARD_AGENT=<name> roll init"
_i18n_set zh init.onboard_switch "换一个 agent:           ROLL_ONBOARD_AGENT=<name> roll init"

# ── migrate ──
_i18n_set en migrate.tips.inspect "Inspect the migration commit"
_i18n_set zh migrate.tips.inspect "查看迁移提交"
_i18n_set en migrate.tips.verify "Verify new structure"
_i18n_set zh migrate.tips.verify "验证新结构"

# ── peer help ──
_i18n_set en peer.help.from "Originating agent"
_i18n_set zh peer.help.from "发起方"
_i18n_set en peer.help.to "Target peer (auto-detected if omitted)"
_i18n_set zh peer.help.to "对端 peer（省略则自动选择）"
_i18n_set en peer.help.round "Current round (default: 1)"
_i18n_set zh peer.help.round "当前轮数"
_i18n_set en peer.help.tag "Task type for routing (architecture, security, test...)"
_i18n_set zh peer.help.tag "任务类型"
_i18n_set en peer.help.context "Context file to send to peer"
_i18n_set zh peer.help.context "上下文文件"
_i18n_set en peer.help.yes "Skip opt-out prompt"
_i18n_set zh peer.help.yes "跳过确认提示"
_i18n_set en peer.help.status_cmd "Show peer review state"
_i18n_set zh peer.help.status_cmd "显示状态"

# ── agent ──
_i18n_set en agent.use_hint "roll agent use <name>   — switch agent for this project"
_i18n_set zh agent.use_hint "roll agent use <name>   — 切换此项目的 agent"
_i18n_set en agent.list_hint "roll agent list         — show installed agents"
_i18n_set zh agent.list_hint "roll agent list         — 查看已安装的 agent"

# ── offboard ──
_i18n_set en offboard.manual_rm_agents "rm -f AGENTS.md CLAUDE.md      # only if they were generated by roll init"
_i18n_set zh offboard.manual_rm_agents "rm -f AGENTS.md CLAUDE.md      # 仅当这些文件由 roll init 生成"
_i18n_set en offboard.manual_rm_roll "rm -rf .roll/                  # all process artefacts"
_i18n_set zh offboard.manual_rm_roll "rm -rf .roll/                  # 所有过程文件"
_i18n_set en offboard.manual_edit_gitignore "Edit .gitignore to remove any '.roll/' entry"
_i18n_set zh offboard.manual_edit_gitignore "编辑 .gitignore 移除 '.roll/' 条目"

# ── doctor ──
_i18n_set en doctor.stale_plists "Stale launchd plists"
_i18n_set zh doctor.stale_plists "无效的 launchd 服务"
_i18n_set en doctor.stale_plists_path "Path no longer valid, clean up with:"
_i18n_set zh doctor.stale_plists_path "路径已失效，可清理:"

# ── check_structure (US-ONBOARD-004) ──
_i18n_set en check_structure.detected "Legacy structure detected at: %s"
_i18n_set zh check_structure.detected "发现老结构目录: %s"
_i18n_set en check_structure.pre_2_0_layout "This project uses the pre-2.0 layout (BACKLOG.md / docs/*). Roll 2.0 requires"
_i18n_set zh check_structure.pre_2_0_layout "此项目使用 2.0 之前的老结构 (BACKLOG.md / docs/*)。Roll 2.0 要求"
_i18n_set en check_structure.run_migration "process artifacts to live in .roll/. Run the migration to upgrade:"
_i18n_set zh check_structure.run_migration "过程文件放在 .roll/ 下。运行迁移命令升级:"
_i18n_set en check_structure.preview_changes "# Preview changes"
_i18n_set zh check_structure.preview_changes "# 预览变更"
_i18n_set en check_structure.execute "# Execute (single atomic commit)"
_i18n_set zh check_structure.execute "# 执行（单次原子提交）"
_i18n_set en check_structure.migration_guide "Migration guide"
_i18n_set zh check_structure.migration_guide "迁移指南"
_i18n_set en check_structure.roll_back "To roll back to Roll 1.x temporarily"
_i18n_set zh check_structure.roll_back "如需临时回退到 Roll 1.x"

# ── main dispatch ──
_i18n_set en main.unknown_command "Unknown command: %s"
_i18n_set zh main.unknown_command "未知命令: %s"

# ── dashboard status ──
_i18n_set en dashboard.pending "pending"
_i18n_set zh dashboard.pending "待办"
