#!/usr/bin/env bats
# FIX-031: Tests for inner script LOCK (second-level lock).
#
# The inner script (generated by _write_loop_runner_script alongside the outer
# runner.sh) must hold an INNER_LOCK around the claude invocation, so a second
# claude session cannot run concurrently even if the outer runner.sh LOCK is
# somehow bypassed (recovery path, direct invocation, race).
#
# LOCK file format: <PID>:<unix_start_ts>  (colon-separated, single line)
# Lock is considered "held" iff: kill -0 <PID> succeeds AND (now - ts) < 14400 (4h).

load helpers

setup() {
  unit_setup_cd
  _test_dir="$TEST_TMP"
}
teardown() {
  unit_teardown_cd
}

# --- Template structure tests ---

@test "_write_loop_runner_script: inner script declares INNER_LOCK path" {
  local script_path="${_test_dir}/run-test-fmt.sh"
  _write_loop_runner_script "$script_path" "/tmp/proj" "echo hi" "/tmp/log" 10 18
  local inner="${script_path%.sh}-inner.sh"
  [ -f "$inner" ]
  grep -qF '.INNER-LOCK-' "$inner"
}

@test "_write_loop_runner_script: inner script writes PID:ts to INNER_LOCK" {
  local script_path="${_test_dir}/run-test-fmt.sh"
  _write_loop_runner_script "$script_path" "/tmp/proj" "echo hi" "/tmp/log" 10 18
  local inner="${script_path%.sh}-inner.sh"
  # Writes "$$:<unix_ts>" — verify both pieces present
  grep -qF '$$' "$inner"
  grep -qE 'date.*\+%s' "$inner"
}

@test "_write_loop_runner_script: inner script traps EXIT to remove INNER_LOCK" {
  local script_path="${_test_dir}/run-test-trap.sh"
  _write_loop_runner_script "$script_path" "/tmp/proj" "echo hi" "/tmp/log" 10 18
  local inner="${script_path%.sh}-inner.sh"
  grep -qE "trap.*INNER_LOCK.*EXIT" "$inner"
}

@test "_write_loop_runner_script: inner script checks alive PID with kill -0" {
  local script_path="${_test_dir}/run-test-check.sh"
  _write_loop_runner_script "$script_path" "/tmp/proj" "echo hi" "/tmp/log" 10 18
  local inner="${script_path%.sh}-inner.sh"
  grep -qF 'kill -0' "$inner"
}

# --- Behaviour tests ---

@test "inner script: concurrent invocation — second instance skips cmd" {
  local script_path="${_test_dir}/run-test-conc.sh"
  local marker="${_test_dir}/marker"
  # cmd writes one marker line then sleeps so the second instance has time
  # to attempt while the lock is held.
  local cmd="echo marker >> '${marker}' && sleep 2"
  _write_loop_runner_script "$script_path" "${_test_dir}" "$cmd" "/tmp/log" 0 24
  local inner="${script_path%.sh}-inner.sh"

  HOME="${_test_dir}" bash "$inner" &
  local pid1=$!
  sleep 0.3  # give first instance time to acquire INNER_LOCK

  HOME="${_test_dir}" bash "$inner"
  local exit2=$?

  wait "$pid1"

  [ "$exit2" -eq 0 ]
  [ -f "$marker" ]
  local count; count=$(wc -l < "$marker" | tr -d ' ')
  [ "$count" -eq 1 ]
}

@test "inner script: stale INNER_LOCK with dead PID is cleaned and cmd runs" {
  local script_path="${_test_dir}/run-test-stale.sh"
  local marker="${_test_dir}/marker"
  local cmd="echo marker >> '${marker}'"
  _write_loop_runner_script "$script_path" "${_test_dir}" "$cmd" "/tmp/log" 0 24
  local inner="${script_path%.sh}-inner.sh"

  local lock_dir; lock_dir="$(dirname "$inner")"
  local lock_base; lock_base="$(basename "$inner" -inner.sh | sed 's/^run-//')"
  local lock_file="${lock_dir}/.INNER-LOCK-${lock_base}"
  # Plant LOCK with PID 99999 (effectively guaranteed dead) + recent ts
  echo "99999:$(date -u +%s)" > "$lock_file"

  HOME="${_test_dir}" bash "$inner"
  local exit_code=$?

  [ "$exit_code" -eq 0 ]
  [ -f "$marker" ]
  [ ! -f "$lock_file" ]  # trap removed it on exit
}

@test "inner script: INNER_LOCK older than 4h is treated as stale" {
  local script_path="${_test_dir}/run-test-aged.sh"
  local marker="${_test_dir}/marker"
  local cmd="echo marker >> '${marker}'"
  _write_loop_runner_script "$script_path" "${_test_dir}" "$cmd" "/tmp/log" 0 24
  local inner="${script_path%.sh}-inner.sh"

  local lock_dir; lock_dir="$(dirname "$inner")"
  local lock_base; lock_base="$(basename "$inner" -inner.sh | sed 's/^run-//')"
  local lock_file="${lock_dir}/.INNER-LOCK-${lock_base}"
  # Plant LOCK with alive PID (self) but ancient ts (epoch=1 → 1970)
  echo "$$:1" > "$lock_file"

  HOME="${_test_dir}" bash "$inner"
  local exit_code=$?

  [ "$exit_code" -eq 0 ]
  [ -f "$marker" ]
}
