#!/usr/bin/env bats
# Tests for loop runner script LOCK mechanism (US-AUTO-022)
#
# The runner script (generated by _write_loop_runner_script) must:
#   1. Write a LOCK file with current PID after the active-window check passes
#   2. Set a trap to remove the LOCK on exit (normal or error)
#   3. Detect an existing LOCK: alive PID → exit 0; dead PID → clean and continue

ROLL_BIN="${BATS_TEST_DIRNAME}/../../bin/roll"

setup() {
  source "$ROLL_BIN"
  _orig_dir="$PWD"
  _test_dir=$(mktemp -d)
  cd "$_test_dir"
}

teardown() {
  cd "$_orig_dir"
  rm -rf "$_test_dir"
}

@test "_write_loop_runner_script: writes LOCK file with current PID" {
  local script_path="${_test_dir}/run-test-abc123.sh"
  _write_loop_runner_script "$script_path" "/tmp/proj" "echo hi" "/tmp/log" 10 18
  grep -qF 'echo "$$"' "$script_path"
  grep -qF '.LOCK-' "$script_path"
}
