#!/usr/bin/env bats
# Tests for roll-doc SKILL.md content invariants (US-SKILL-008)

SKILL="${BATS_TEST_DIRNAME}/../../skills/roll-doc/SKILL.md"

@test "roll-doc SKILL.md: exists" {
  [ -f "$SKILL" ]
}

@test "roll-doc SKILL.md: has required frontmatter fields" {
  grep -qE '^name: roll-doc' "$SKILL"
  grep -qE '^license: MIT' "$SKILL"
  grep -qE '^allowed-tools:' "$SKILL"
  grep -qE '^description:' "$SKILL"
}

@test "roll-doc SKILL.md: documents all four phases" {
  grep -qiE 'Phase 1.*Scan' "$SKILL"
  grep -qiE 'Phase 2.*Gap' "$SKILL"
  grep -qiE 'Phase 3.*Fill' "$SKILL"
  grep -qiE 'Phase 4.*Report' "$SKILL"
}

@test "roll-doc SKILL.md: specifies docs/INDEX.md as output" {
  grep -qF 'docs/INDEX.md' "$SKILL"
}

@test "roll-doc SKILL.md: includes draft header text" {
  grep -qF 'Draft' "$SKILL"
  grep -qF 'auto-generated by roll-doc' "$SKILL"
}

@test "roll-doc SKILL.md: documents --dry-run flag" {
  grep -qF -- '--dry-run' "$SKILL"
}

@test "roll-doc SKILL.md: documents --force flag" {
  grep -qF -- '--force' "$SKILL"
}

@test "roll-doc SKILL.md: lists scan exclusions including node_modules and .git" {
  grep -qF 'node_modules' "$SKILL"
  grep -qF '.git' "$SKILL"
  grep -qF 'docs/dream' "$SKILL"
  grep -qF 'docs/briefs' "$SKILL"
}

@test "roll-doc SKILL.md: documents convention file detection" {
  grep -qF 'AGENTS.md' "$SKILL"
  grep -qF 'CLAUDE.md' "$SKILL"
  grep -qF 'ARCHITECTURE.md' "$SKILL"
}

@test "roll-doc SKILL.md: has When to Use and When Not to Use sections" {
  grep -qE '^## When to Use' "$SKILL"
  grep -qE '^## When Not to Use' "$SKILL"
}

@test "roll-doc SKILL.md: idempotency rule documented" {
  grep -qiE 'no.op|idempoten' "$SKILL"
}
